# biblioteca/vocabulario/base/cuerpo_humano.py
CUERPO_HUMANO = {
    'cabeza':      {'id': 'CUERPO_CABEZA',    'tipo': 'parte_cuerpo', 'grounding_base': 0.90, 'variantes': ['cabezas', 'cabecita']},
    'cara':        {'id': 'CUERPO_CARA',      'tipo': 'parte_cuerpo', 'grounding_base': 0.90, 'variantes': ['caras', 'rostro', 'faz']},
    'ojo':         {'id': 'CUERPO_OJO',       'tipo': 'parte_cuerpo', 'grounding_base': 0.90, 'variantes': ['ojos', 'ojitos', 'mirada']},
    'nariz':       {'id': 'CUERPO_NARIZ',     'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['narices']},
    'boca':        {'id': 'CUERPO_BOCA',      'tipo': 'parte_cuerpo', 'grounding_base': 0.90, 'variantes': ['bocas', 'boquita']},
    'oído':        {'id': 'CUERPO_OIDO',      'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['oido', 'oídos', 'oreja', 'orejas']},
    'pelo':        {'id': 'CUERPO_PELO',      'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['cabello', 'cabellos', 'pelito']},
    'cuello':      {'id': 'CUERPO_CUELLO',    'tipo': 'parte_cuerpo', 'grounding_base': 0.85, 'variantes': ['cuellos']},
    'hombro':      {'id': 'CUERPO_HOMBRO',    'tipo': 'parte_cuerpo', 'grounding_base': 0.85, 'variantes': ['hombros']},
    'brazo':       {'id': 'CUERPO_BRAZO',     'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['brazos', 'bracito']},
    'mano':        {'id': 'CUERPO_MANO',      'tipo': 'parte_cuerpo', 'grounding_base': 0.90, 'variantes': ['manos', 'manita']},
    'dedo':        {'id': 'CUERPO_DEDO',      'tipo': 'parte_cuerpo', 'grounding_base': 0.87, 'variantes': ['dedos', 'dedito']},
    'pecho':       {'id': 'CUERPO_PECHO',     'tipo': 'parte_cuerpo', 'grounding_base': 0.87, 'variantes': ['pechos', 'tórax', 'torax']},
    'espalda':     {'id': 'CUERPO_ESPALDA',   'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['espaldas', 'dorso']},
    'estómago':    {'id': 'CUERPO_ESTOMAGO',  'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['estomago', 'barriga', 'panza', 'abdomen']},
    'pierna':      {'id': 'CUERPO_PIERNA',    'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['piernas']},
    'rodilla':     {'id': 'CUERPO_RODILLA',   'tipo': 'parte_cuerpo', 'grounding_base': 0.85, 'variantes': ['rodillas']},
    'pie':         {'id': 'CUERPO_PIE',       'tipo': 'parte_cuerpo', 'grounding_base': 0.88, 'variantes': ['pies', 'piecito']},
    'corazón':     {'id': 'CUERPO_CORAZON',   'tipo': 'organo', 'grounding_base': 0.92, 'variantes': ['corazon', 'corazones', 'corazoncito']},
    'cerebro':     {'id': 'CUERPO_CEREBRO',   'tipo': 'organo', 'grounding_base': 0.90, 'variantes': ['cerebros', 'mente', 'cabeza']},
    'pulmón':      {'id': 'CUERPO_PULMON',    'tipo': 'organo', 'grounding_base': 0.85, 'variantes': ['pulmon', 'pulmones']},
    'sangre':      {'id': 'CUERPO_SANGRE',    'tipo': 'organo', 'grounding_base': 0.87, 'variantes': ['sangrar', 'hemorragia']},
    'piel':        {'id': 'CUERPO_PIEL',      'tipo': 'parte_cuerpo', 'grounding_base': 0.87, 'variantes': ['pieles', 'cutis']},
    'cuerpo':      {'id': 'CUERPO_CONCEPTO',  'tipo': 'concepto_cuerpo', 'grounding_base': 0.90, 'variantes': ['cuerpos', 'físico', 'fisico']},
    'voz':         {'id': 'CUERPO_VOZ',       'tipo': 'capacidad_fisica', 'grounding_base': 0.90, 'variantes': ['voces', 'vocecita', 'hablar']},
}
