# biblioteca/vocabulario/base/educacion.py
EDUCACION = {
    'estudiar':    {'id': 'EDU_ESTUDIAR',  'tipo': 'accion_educativa', 'grounding_base': 0.92, 'variantes': ['estudiando', 'estudié', 'estudio', 'estudias']},
    'aprender':    {'id': 'EDU_APRENDER',  'tipo': 'accion_educativa', 'grounding_base': 0.93, 'variantes': ['aprendiendo', 'aprendí', 'aprendo', 'aprende']},
    'enseñar':     {'id': 'EDU_ENSENAR',   'tipo': 'accion_educativa', 'grounding_base': 0.88, 'variantes': ['enseñando', 'enseñé', 'enseño', 'enseña']},
    'entender':    {'id': 'EDU_ENTENDER',  'tipo': 'accion_cognitiva', 'grounding_base': 0.93, 'variantes': ['entendiendo', 'entendí', 'entiendo', 'comprendo', 'comprender']},
    'escuela':     {'id': 'EDU_ESCUELA',   'tipo': 'institucion',      'grounding_base': 0.90, 'variantes': ['colegio', 'colegio público', 'bachillerato']},
    'universidad': {'id': 'EDU_UNIVERSIDAD','tipo': 'institucion',     'grounding_base': 0.90, 'variantes': ['universidad', 'uni', 'facultad', 'carrera universitaria']},
    'clase':       {'id': 'EDU_CLASE',     'tipo': 'evento_educativo', 'grounding_base': 0.90, 'variantes': ['clases', 'lección', 'leccion', 'sesión educativa']},
    'profesor':    {'id': 'EDU_PROFESOR',  'tipo': 'rol_educativo',    'grounding_base': 0.90, 'variantes': ['profesora', 'maestro', 'maestra', 'docente', 'teacher']},
    'estudiante':  {'id': 'EDU_ESTUDIANTE','tipo': 'rol_educativo',    'grounding_base': 0.88, 'variantes': ['alumno', 'alumna', 'alumnos', 'estudiantes']},
    'examen':      {'id': 'EDU_EXAMEN',    'tipo': 'evaluacion',       'grounding_base': 0.92, 'variantes': ['exámenes', 'examenes', 'prueba', 'test', 'evaluación']},
    'nota':        {'id': 'EDU_NOTA',      'tipo': 'evaluacion',       'grounding_base': 0.88, 'variantes': ['notas', 'calificación', 'calificacion', 'grade']},
    'reprobar':    {'id': 'EDU_REPROBAR',  'tipo': 'resultado',        'grounding_base': 0.90, 'variantes': ['reprobé', 'perdí el año', 'me jalaron', 'perdí el examen', 'perdi']},
    'aprobar':     {'id': 'EDU_APROBAR',   'tipo': 'resultado',        'grounding_base': 0.88, 'variantes': ['aprobé', 'pasé el examen', 'gané el año']},
    'tarea':       {'id': 'EDU_TAREA',     'tipo': 'actividad',        'grounding_base': 0.90, 'variantes': ['tareas', 'homework', 'trabajo escolar']},
    'conocimiento':{'id': 'EDU_CONOCIMIENTO','tipo': 'concepto',       'grounding_base': 0.90, 'variantes': ['conocimientos', 'saber', 'sabiduría']},
    'error':       {'id': 'EDU_ERROR',     'tipo': 'resultado',        'grounding_base': 0.92, 'variantes': ['errores', 'equivocación', 'fallo', 'bug', 'me equivoqué']},
    'practicar':   {'id': 'EDU_PRACTICAR', 'tipo': 'accion_educativa', 'grounding_base': 0.88, 'variantes': ['práctica', 'practica', 'practicando', 'ejercitar']},
    'investigar':  {'id': 'EDU_INVESTIGAR','tipo': 'accion_cognitiva', 'grounding_base': 0.87, 'variantes': ['investigando', 'investigué', 'buscar información']},
    'explicar':    {'id': 'EDU_EXPLICAR',  'tipo': 'accion_cognitiva', 'grounding_base': 0.90, 'variantes': ['explicando', 'explícame', 'explicame', 'cuéntame', 'cuéntame cómo']},
    'pregunta':    {'id': 'EDU_PREGUNTA',  'tipo': 'accion_cognitiva', 'grounding_base': 0.90, 'variantes': ['preguntas', 'tengo una pregunta', 'pregunto', 'duda']},
    'respuesta':   {'id': 'EDU_RESPUESTA', 'tipo': 'concepto',         'grounding_base': 0.90, 'variantes': ['respuestas', 'la respuesta', 'responder', 'contestar']},
    'difícil':     {'id': 'EDU_DIFICIL',   'tipo': 'valoracion',       'grounding_base': 0.92, 'variantes': ['dificil', 'difíciles', 'complicado', 'no entiendo', 'no comprendo']},
    'fácil':       {'id': 'EDU_FACIL',     'tipo': 'valoracion',       'grounding_base': 0.88, 'variantes': ['facil', 'sencillo', 'obvio', 'simple']},
    'listo':       {'id': 'EDU_LISTO',     'tipo': 'resultado',        'grounding_base': 0.87, 'variantes': ['ya sé', 'ya aprendí', 'ya entendí', 'captado']},
    'duda':        {'id': 'EDU_DUDA',      'tipo': 'estado_cognitivo', 'grounding_base': 0.90, 'variantes': ['dudas', 'tengo una duda', 'no sé si', 'incertidumbre']},
}
