# biblioteca/vocabulario/base/familia.py
FAMILIA = {
    'mamá':       {'id': 'FAM_MAMA',      'tipo': 'familiar', 'grounding_base': 0.95, 'variantes': ['mama', 'madre', 'mami', 'ma']},
    'papá':       {'id': 'FAM_PAPA',      'tipo': 'familiar', 'grounding_base': 0.95, 'variantes': ['papa', 'padre', 'papi', 'pa']},
    'hermano':    {'id': 'FAM_HERMANO',   'tipo': 'familiar', 'grounding_base': 0.93, 'variantes': ['hermana', 'hermanos', 'hermanito', 'hermanita']},
    'hijo':       {'id': 'FAM_HIJO',      'tipo': 'familiar', 'grounding_base': 0.93, 'variantes': ['hija', 'hijos', 'hijito', 'hijita']},
    'abuelo':     {'id': 'FAM_ABUELO',    'tipo': 'familiar', 'grounding_base': 0.90, 'variantes': ['abuela', 'abuelos', 'abuelito', 'abuelita']},
    'tío':        {'id': 'FAM_TIO',       'tipo': 'familiar', 'grounding_base': 0.88, 'variantes': ['tio', 'tía', 'tia', 'tíos']},
    'primo':      {'id': 'FAM_PRIMO',     'tipo': 'familiar', 'grounding_base': 0.88, 'variantes': ['prima', 'primos', 'primas']},
    'esposo':     {'id': 'FAM_ESPOSO',    'tipo': 'familiar', 'grounding_base': 0.90, 'variantes': ['esposa', 'marido', 'mujer', 'cónyuge']},
    'novio':      {'id': 'FAM_NOVIO',     'tipo': 'familiar', 'grounding_base': 0.90, 'variantes': ['novia', 'novios', 'pareja', 'mi novio', 'mi novia']},
    'bebé':       {'id': 'FAM_BEBE',      'tipo': 'familiar', 'grounding_base': 0.88, 'variantes': ['bebe', 'bebés', 'niño', 'niña', 'infante']},
    'familia':    {'id': 'FAM_FAMILIA',   'tipo': 'concepto_familiar', 'grounding_base': 0.92, 'variantes': ['familias', 'mi familia', 'la familia']},
    'pariente':   {'id': 'FAM_PARIENTE',  'tipo': 'concepto_familiar', 'grounding_base': 0.83, 'variantes': ['parientes', 'familiar', 'familiares']},
    'amigo':      {'id': 'FAM_AMIGO',     'tipo': 'relacion_social',   'grounding_base': 0.92, 'variantes': ['amiga', 'amigos', 'amigas', 'mi amigo', 'mi amiga']},
    'conocido':   {'id': 'FAM_CONOCIDO',  'tipo': 'relacion_social',   'grounding_base': 0.83, 'variantes': ['conocida', 'conocidos']},
    'vecino':     {'id': 'FAM_VECINO',    'tipo': 'relacion_social',   'grounding_base': 0.85, 'variantes': ['vecina', 'vecinos']},
    'persona':    {'id': 'FAM_PERSONA',   'tipo': 'concepto_social',   'grounding_base': 0.88, 'variantes': ['personas', 'gente', 'individuo']},
    'alguien':    {'id': 'FAM_ALGUIEN',   'tipo': 'concepto_social',   'grounding_base': 0.87, 'variantes': []},
    'nadie':      {'id': 'FAM_NADIE',     'tipo': 'concepto_social',   'grounding_base': 0.87, 'variantes': []},
    'todos':      {'id': 'FAM_TODOS',     'tipo': 'concepto_social',   'grounding_base': 0.87, 'variantes': ['todas', 'todo el mundo', 'la gente']},
    'mascota':    {'id': 'FAM_MASCOTA',   'tipo': 'relacion_social',   'grounding_base': 0.85, 'variantes': ['mascotas', 'perro', 'gato', 'mi mascota']},
    'perro':      {'id': 'FAM_PERRO',     'tipo': 'animal_compania',   'grounding_base': 0.87, 'variantes': ['perros', 'perrita', 'perrito', 'can']},
    'gato':       {'id': 'FAM_GATO',      'tipo': 'animal_compania',   'grounding_base': 0.87, 'variantes': ['gatos', 'gatito', 'gatita', 'michi']},
}
