# biblioteca/vocabulario/base/hogar.py
HOGAR = {
    'casa':        {'id': 'HOGAR_CASA',     'tipo': 'espacio_hogar', 'grounding_base': 0.93, 'variantes': ['casas', 'hogar', 'hogares', 'casita']},
    'apartamento': {'id': 'HOGAR_APTO',     'tipo': 'espacio_hogar', 'grounding_base': 0.88, 'variantes': ['apto', 'departamento', 'piso', 'apartamento']},
    'cuarto':      {'id': 'HOGAR_CUARTO',   'tipo': 'habitacion',    'grounding_base': 0.90, 'variantes': ['cuartos', 'habitación', 'habitacion', 'pieza', 'recámara']},
    'sala':        {'id': 'HOGAR_SALA',     'tipo': 'habitacion',    'grounding_base': 0.88, 'variantes': ['salas', 'living', 'salón', 'salon']},
    'cocina':      {'id': 'HOGAR_COCINA',   'tipo': 'habitacion',    'grounding_base': 0.90, 'variantes': ['cocinas']},
    'baño':        {'id': 'HOGAR_BANO',     'tipo': 'habitacion',    'grounding_base': 0.90, 'variantes': ['bano', 'baños', 'sanitario', 'servicio']},
    'cama':        {'id': 'HOGAR_CAMA',     'tipo': 'mueble',        'grounding_base': 0.92, 'variantes': ['camas', 'camita', 'colchón']},
    'mesa':        {'id': 'HOGAR_MESA',     'tipo': 'mueble',        'grounding_base': 0.88, 'variantes': ['mesas', 'escritorio']},
    'silla':       {'id': 'HOGAR_SILLA',    'tipo': 'mueble',        'grounding_base': 0.87, 'variantes': ['sillas', 'asiento', 'sillón', 'sillon']},
    'puerta':      {'id': 'HOGAR_PUERTA',   'tipo': 'estructura',    'grounding_base': 0.88, 'variantes': ['puertas', 'portalón']},
    'ventana':     {'id': 'HOGAR_VENTANA',  'tipo': 'estructura',    'grounding_base': 0.87, 'variantes': ['ventanas', 'vidrio']},
    'piso':        {'id': 'HOGAR_PISO',     'tipo': 'estructura',    'grounding_base': 0.85, 'variantes': ['pisos', 'suelo', 'planta baja']},
    'techo':       {'id': 'HOGAR_TECHO',    'tipo': 'estructura',    'grounding_base': 0.85, 'variantes': ['techos', 'teja', 'tejado']},
    'nevera':      {'id': 'HOGAR_NEVERA',   'tipo': 'electrodomestico','grounding_base': 0.88,'variantes': ['refrigerador', 'heladera', 'frío']},
    'estufa':      {'id': 'HOGAR_ESTUFA',   'tipo': 'electrodomestico','grounding_base': 0.87,'variantes': ['estufas', 'fogón', 'horno', 'cocina a gas']},
    'computador':  {'id': 'HOGAR_PC',       'tipo': 'electrodomestico','grounding_base': 0.90,'variantes': ['computadora', 'pc', 'portátil', 'portatil', 'laptop']},
    'celular':     {'id': 'HOGAR_CELULAR',  'tipo': 'electrodomestico','grounding_base': 0.92,'variantes': ['teléfono', 'telefono', 'móvil', 'movil', 'cel', 'smartphone']},
    'televisor':   {'id': 'HOGAR_TV',       'tipo': 'electrodomestico','grounding_base': 0.88,'variantes': ['televisión', 'television', 'tele', 'tv']},
    'luz':         {'id': 'HOGAR_LUZ',      'tipo': 'servicio_hogar','grounding_base': 0.87, 'variantes': ['luces', 'electricidad', 'bombillo']},
    'agua':        {'id': 'HOGAR_AGUA',     'tipo': 'servicio_hogar','grounding_base': 0.90, 'variantes': ['aguas', 'llave', 'ducha', 'grifo']},
    'llave':       {'id': 'HOGAR_LLAVE',    'tipo': 'objeto_hogar',  'grounding_base': 0.85, 'variantes': ['llaves', 'llavecita']},
    'escalera':    {'id': 'HOGAR_ESCALERA', 'tipo': 'estructura',    'grounding_base': 0.83, 'variantes': ['escaleras', 'escalón']},
    'garaje':      {'id': 'HOGAR_GARAJE',   'tipo': 'espacio_hogar', 'grounding_base': 0.83, 'variantes': ['garage', 'parqueadero']},
}
