# biblioteca/vocabulario/base/numeros_cantidades.py
NUMEROS_CANTIDADES = {

    # ── NÚMEROS CARDINALES ───────────────────────
    'cero':        {'id': 'NUM_0',   'tipo': 'numero_cardinal', 'grounding_base': 0.90, 'variantes': ['0']},
    'uno':         {'id': 'NUM_1',   'tipo': 'numero_cardinal', 'grounding_base': 0.90, 'variantes': ['una', '1', 'primero']},
    'dos':         {'id': 'NUM_2',   'tipo': 'numero_cardinal', 'grounding_base': 0.90, 'variantes': ['2', 'segundo']},
    'tres':        {'id': 'NUM_3',   'tipo': 'numero_cardinal', 'grounding_base': 0.90, 'variantes': ['3', 'tercero']},
    'cuatro':      {'id': 'NUM_4',   'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['4', 'cuarto']},
    'cinco':       {'id': 'NUM_5',   'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['5', 'quinto']},
    'seis':        {'id': 'NUM_6',   'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['6', 'sexto']},
    'siete':       {'id': 'NUM_7',   'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['7', 'séptimo']},
    'ocho':        {'id': 'NUM_8',   'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['8', 'octavo']},
    'nueve':       {'id': 'NUM_9',   'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['9', 'noveno']},
    'diez':        {'id': 'NUM_10',  'tipo': 'numero_cardinal', 'grounding_base': 0.88, 'variantes': ['10', 'décimo']},
    'once':        {'id': 'NUM_11',  'tipo': 'numero_cardinal', 'grounding_base': 0.85, 'variantes': ['11']},
    'doce':        {'id': 'NUM_12',  'tipo': 'numero_cardinal', 'grounding_base': 0.85, 'variantes': ['12']},
    'veinte':      {'id': 'NUM_20',  'tipo': 'numero_cardinal', 'grounding_base': 0.85, 'variantes': ['20', 'veinti']},
    'treinta':     {'id': 'NUM_30',  'tipo': 'numero_cardinal', 'grounding_base': 0.83, 'variantes': ['30']},
    'cuarenta':    {'id': 'NUM_40',  'tipo': 'numero_cardinal', 'grounding_base': 0.83, 'variantes': ['40']},
    'cincuenta':   {'id': 'NUM_50',  'tipo': 'numero_cardinal', 'grounding_base': 0.83, 'variantes': ['50']},
    'cien':        {'id': 'NUM_100', 'tipo': 'numero_cardinal', 'grounding_base': 0.85, 'variantes': ['100', 'ciento']},
    'mil':         {'id': 'NUM_1000','tipo': 'numero_cardinal', 'grounding_base': 0.85, 'variantes': ['1000', 'miles']},
    'millón':      {'id': 'NUM_1M',  'tipo': 'numero_cardinal', 'grounding_base': 0.83, 'variantes': ['millon', 'millones']},

    # ── CANTIDADES RELATIVAS ─────────────────────
    'mucho':       {'id': 'CANT_MUCHO',     'tipo': 'cantidad_relativa', 'grounding_base': 0.90, 'variantes': ['mucha', 'muchos', 'muchas', 'bastante']},
    'poco':        {'id': 'CANT_POCO',      'tipo': 'cantidad_relativa', 'grounding_base': 0.90, 'variantes': ['poca', 'pocos', 'pocas']},
    'nada':        {'id': 'CANT_NADA',      'tipo': 'cantidad_relativa', 'grounding_base': 0.90, 'variantes': []},
    'todo':        {'id': 'CANT_TODO',      'tipo': 'cantidad_relativa', 'grounding_base': 0.90, 'variantes': ['toda', 'todos', 'todas']},
    'más':         {'id': 'CANT_MAS',       'tipo': 'cantidad_relativa', 'grounding_base': 0.90, 'variantes': ['mas']},
    'menos':       {'id': 'CANT_MENOS',     'tipo': 'cantidad_relativa', 'grounding_base': 0.90, 'variantes': []},
    'demasiado':   {'id': 'CANT_DEMASIADO', 'tipo': 'cantidad_relativa', 'grounding_base': 0.87, 'variantes': ['demasiada', 'demasiados', 'demasiadas', 'demasiado']},
    'suficiente':  {'id': 'CANT_SUFICIENTE','tipo': 'cantidad_relativa', 'grounding_base': 0.85, 'variantes': ['suficientes', 'bastante', 'suficiente']},
    'varios':      {'id': 'CANT_VARIOS',    'tipo': 'cantidad_relativa', 'grounding_base': 0.83, 'variantes': ['varias', 'algunos', 'algunas']},
    'ninguno':     {'id': 'CANT_NINGUNO',   'tipo': 'cantidad_relativa', 'grounding_base': 0.87, 'variantes': ['ninguna', 'ningún', 'ningun']},
    'solo':        {'id': 'CANT_SOLO',      'tipo': 'cantidad_relativa', 'grounding_base': 0.85, 'variantes': ['sola', 'solamente', 'únicamente', 'unicamente']},
    'casi':        {'id': 'CANT_CASI',      'tipo': 'cantidad_relativa', 'grounding_base': 0.87, 'variantes': ['casi todo', 'casi nada']},
    'exactamente': {'id': 'CANT_EXACTO',    'tipo': 'cantidad_relativa', 'grounding_base': 0.85, 'variantes': ['exacto', 'exacta', 'justo', 'preciso']},
    'aproximado':  {'id': 'CANT_APROX',     'tipo': 'cantidad_relativa', 'grounding_base': 0.82, 'variantes': ['aproximadamente', 'más o menos', 'como unos']},
    'la mitad':    {'id': 'CANT_MITAD',     'tipo': 'cantidad_relativa', 'grounding_base': 0.83, 'variantes': ['mitad', 'la mitad de']},
    'el doble':    {'id': 'CANT_DOBLE',     'tipo': 'cantidad_relativa', 'grounding_base': 0.82, 'variantes': ['doble', 'dos veces']},
    'ambos':       {'id': 'CANT_AMBOS',     'tipo': 'cantidad_relativa', 'grounding_base': 0.83, 'variantes': ['ambas', 'los dos', 'las dos']},
    'cada uno':    {'id': 'CANT_CADA_UNO',  'tipo': 'cantidad_relativa', 'grounding_base': 0.83, 'variantes': ['cada cual', 'cada persona']},

    # ── OPERACIONES MATEMÁTICAS ──────────────────
    'suma':        {'id': 'MAT_SUMA',    'tipo': 'operacion_matematica', 'grounding_base': 0.88, 'variantes': ['sumar', 'más', 'adición']},
    'resta':       {'id': 'MAT_RESTA',   'tipo': 'operacion_matematica', 'grounding_base': 0.88, 'variantes': ['restar', 'menos', 'sustracción']},
    'multiplicar': {'id': 'MAT_MULT',    'tipo': 'operacion_matematica', 'grounding_base': 0.87, 'variantes': ['multiplicación', 'por', 'veces']},
    'dividir':     {'id': 'MAT_DIV',     'tipo': 'operacion_matematica', 'grounding_base': 0.87, 'variantes': ['división', 'entre', 'dividido']},
    'porcentaje':  {'id': 'MAT_PORCENT', 'tipo': 'operacion_matematica', 'grounding_base': 0.85, 'variantes': ['por ciento', '%', 'porciento']},
    'promedio':    {'id': 'MAT_PROM',    'tipo': 'operacion_matematica', 'grounding_base': 0.85, 'variantes': ['media', 'promedio de']},
    'calcular':    {'id': 'MAT_CALCULAR','tipo': 'operacion_matematica', 'grounding_base': 0.88, 'variantes': ['calcula', 'calculame', 'calculo']},
    'resultado':   {'id': 'MAT_RESULT',  'tipo': 'operacion_matematica', 'grounding_base': 0.87, 'variantes': ['respuesta', 'solución', 'solucion']},
    'número':      {'id': 'CONCEPTO_NUM','tipo': 'concepto_numero',      'grounding_base': 0.87, 'variantes': ['numero', 'números', 'numeros', 'cifra', 'dígito']},
    'operación':   {'id': 'CONCEPTO_OP', 'tipo': 'concepto_numero',      'grounding_base': 0.85, 'variantes': ['operacion', 'operaciones', 'cálculo', 'calculo']},
}
