# biblioteca/vocabulario/base/preguntas.py
# ================================================
# PREGUNTAS, REFERENCIAS Y EXPRESIONES
# Expandido para cubrir ~80% del lenguaje natural
# ================================================

PREGUNTAS = {

    # ── INTERROGATIVAS DIRECTAS ──────────────────────────
    'qué':          {'id': 'PREG_QUE',      'grounding': 0.90, 'tipo': 'pregunta'},
    'que':          {'id': 'PREG_QUE',      'grounding': 0.85, 'tipo': 'pregunta'},
    'quién':        {'id': 'PREG_QUIEN',    'grounding': 0.90, 'tipo': 'pregunta'},
    'quien':        {'id': 'PREG_QUIEN',    'grounding': 0.85, 'tipo': 'pregunta'},
    'quiénes':      {'id': 'PREG_QUIENES',  'grounding': 0.90, 'tipo': 'pregunta'},
    'quienes':      {'id': 'PREG_QUIENES',  'grounding': 0.85, 'tipo': 'pregunta'},
    'cómo':         {'id': 'PREG_COMO',     'grounding': 0.90, 'tipo': 'pregunta'},
    'como':         {'id': 'PREG_COMO',     'grounding': 0.85, 'tipo': 'pregunta'},
    'cuándo':       {'id': 'PREG_CUANDO',   'grounding': 0.90, 'tipo': 'pregunta'},
    'cuando':       {'id': 'PREG_CUANDO',   'grounding': 0.85, 'tipo': 'pregunta'},
    'dónde':        {'id': 'PREG_DONDE',    'grounding': 0.90, 'tipo': 'pregunta'},
    'donde':        {'id': 'PREG_DONDE',    'grounding': 0.85, 'tipo': 'pregunta'},
    'por qué':      {'id': 'PREG_POR_QUE',  'grounding': 0.95, 'tipo': 'pregunta'},
    'por que':      {'id': 'PREG_POR_QUE',  'grounding': 0.90, 'tipo': 'pregunta'},
    'porqué':       {'id': 'PREG_POR_QUE',  'grounding': 0.90, 'tipo': 'pregunta'},
    'porque':       {'id': 'PREG_PORQUE',   'grounding': 0.85, 'tipo': 'causa'},
    'para qué':     {'id': 'PREG_PARA_QUE', 'grounding': 0.90, 'tipo': 'pregunta'},
    'para que':     {'id': 'PREG_PARA_QUE', 'grounding': 0.85, 'tipo': 'pregunta'},
    'cuánto':       {'id': 'PREG_CUANTO',   'grounding': 0.90, 'tipo': 'pregunta'},
    'cuanto':       {'id': 'PREG_CUANTO',   'grounding': 0.85, 'tipo': 'pregunta'},
    'cuántos':      {'id': 'PREG_CUANTOS',  'grounding': 0.90, 'tipo': 'pregunta'},
    'cuantos':      {'id': 'PREG_CUANTOS',  'grounding': 0.85, 'tipo': 'pregunta'},
    'cuántas':      {'id': 'PREG_CUANTAS',  'grounding': 0.90, 'tipo': 'pregunta'},
    'cuantas':      {'id': 'PREG_CUANTAS',  'grounding': 0.85, 'tipo': 'pregunta'},
    'cuál':         {'id': 'PREG_CUAL',     'grounding': 0.90, 'tipo': 'pregunta'},
    'cual':         {'id': 'PREG_CUAL',     'grounding': 0.85, 'tipo': 'pregunta'},
    'cuáles':       {'id': 'PREG_CUALES',   'grounding': 0.90, 'tipo': 'pregunta'},
    'cuales':       {'id': 'PREG_CUALES',   'grounding': 0.85, 'tipo': 'pregunta'},

    # ── REFERENCIAS PERSONALES ───────────────────────────
    'yo':           {'id': 'REF_YO',        'grounding': 0.90, 'tipo': 'referencia_personal'},
    'tú':           {'id': 'REF_TU',        'grounding': 0.90, 'tipo': 'referencia_personal'},
    'tu':           {'id': 'REF_TU',        'grounding': 0.85, 'tipo': 'referencia_personal'},
    'él':           {'id': 'REF_EL',        'grounding': 0.85, 'tipo': 'referencia_personal'},
    'ella':         {'id': 'REF_ELLA',      'grounding': 0.85, 'tipo': 'referencia_personal'},
    'nosotros':     {'id': 'REF_NOSOTROS',  'grounding': 0.85, 'tipo': 'referencia_personal'},
    'ustedes':      {'id': 'REF_USTEDES',   'grounding': 0.85, 'tipo': 'referencia_personal'},
    'ellos':        {'id': 'REF_ELLOS',     'grounding': 0.85, 'tipo': 'referencia_personal'},
    'me':           {'id': 'REF_ME',        'grounding': 0.80, 'tipo': 'referencia_personal'},
    'mi':           {'id': 'REF_MI',        'grounding': 0.80, 'tipo': 'referencia_personal'},
    'mí':           {'id': 'REF_MI',        'grounding': 0.80, 'tipo': 'referencia_personal'},
    'te':           {'id': 'REF_TE',        'grounding': 0.80, 'tipo': 'referencia_personal'},
    'le':           {'id': 'REF_LE',        'grounding': 0.75, 'tipo': 'referencia_personal'},
    'nos':          {'id': 'REF_NOS',       'grounding': 0.75, 'tipo': 'referencia_personal'},
    'lo':           {'id': 'REF_LO',        'grounding': 0.70, 'tipo': 'referencia_personal'},
    'la':           {'id': 'REF_LA',        'grounding': 0.65, 'tipo': 'referencia_personal'},

    # ── AFIRMACIÓN Y NEGACIÓN ────────────────────────────
    'sí':           {'id': 'AFIRMACION',        'grounding': 0.95, 'tipo': 'confirmacion'},
    'si':           {'id': 'AFIRMACION',        'grounding': 0.90, 'tipo': 'confirmacion'},
    'no':           {'id': 'NEGACION',          'grounding': 0.95, 'tipo': 'negacion'},
    'claro':        {'id': 'AFIRMACION_FUERTE', 'grounding': 0.90, 'tipo': 'confirmacion'},
    'exacto':       {'id': 'AFIRMACION_FUERTE', 'grounding': 0.90, 'tipo': 'confirmacion'},
    'correcto':     {'id': 'AFIRMACION_FUERTE', 'grounding': 0.90, 'tipo': 'confirmacion'},
    'así es':       {'id': 'AFIRMACION_FUERTE', 'grounding': 0.90, 'tipo': 'confirmacion'},
    'asi es':       {'id': 'AFIRMACION_FUERTE', 'grounding': 0.90, 'tipo': 'confirmacion'},
    'efectivamente':{'id': 'AFIRMACION_FUERTE', 'grounding': 0.90, 'tipo': 'confirmacion'},
    'nunca':        {'id': 'NEGACION_FUERTE',   'grounding': 0.90, 'tipo': 'negacion'},
    'jamás':        {'id': 'NEGACION_FUERTE',   'grounding': 0.90, 'tipo': 'negacion'},
    'tampoco':      {'id': 'NEGACION',          'grounding': 0.85, 'tipo': 'negacion'},
    'para nada':    {'id': 'NEGACION_FUERTE',   'grounding': 0.90, 'tipo': 'negacion'},

    # ── CUANTIFICADORES ──────────────────────────────────
    'todo':         {'id': 'CUANT_TODO',    'grounding': 0.85, 'tipo': 'cuantificador'},
    'todos':        {'id': 'CUANT_TODOS',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'toda':         {'id': 'CUANT_TODO',    'grounding': 0.85, 'tipo': 'cuantificador'},
    'todas':        {'id': 'CUANT_TODOS',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'algo':         {'id': 'CUANT_ALGO',    'grounding': 0.80, 'tipo': 'cuantificador'},
    'nada':         {'id': 'CUANT_NADA',    'grounding': 0.85, 'tipo': 'cuantificador'},
    'mucho':        {'id': 'CUANT_MUCHO',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'mucha':        {'id': 'CUANT_MUCHO',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'muchos':       {'id': 'CUANT_MUCHO',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'muchas':       {'id': 'CUANT_MUCHO',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'poco':         {'id': 'CUANT_POCO',    'grounding': 0.85, 'tipo': 'cuantificador'},
    'pocos':        {'id': 'CUANT_POCO',    'grounding': 0.85, 'tipo': 'cuantificador'},
    'más':          {'id': 'CUANT_MAS',     'grounding': 0.85, 'tipo': 'cuantificador'},
    'mas':          {'id': 'CUANT_MAS',     'grounding': 0.80, 'tipo': 'cuantificador'},
    'menos':        {'id': 'CUANT_MENOS',   'grounding': 0.85, 'tipo': 'cuantificador'},
    'muy':          {'id': 'CUANT_MUY',     'grounding': 0.80, 'tipo': 'intensificador'},
    'bastante':     {'id': 'CUANT_BASTANTE','grounding': 0.80, 'tipo': 'intensificador'},
    'demasiado':    {'id': 'CUANT_DEMASIADO','grounding': 0.80,'tipo': 'intensificador'},
    'suficiente':   {'id': 'CUANT_SUFICIENTE','grounding':0.80, 'tipo': 'cuantificador'},
    'varios':       {'id': 'CUANT_VARIOS',  'grounding': 0.80, 'tipo': 'cuantificador'},
    'algunos':      {'id': 'CUANT_ALGUNOS', 'grounding': 0.80, 'tipo': 'cuantificador'},
    'ningún':       {'id': 'CUANT_NINGUNO', 'grounding': 0.85, 'tipo': 'cuantificador'},
    'ninguno':      {'id': 'CUANT_NINGUNO', 'grounding': 0.85, 'tipo': 'cuantificador'},

    # ── DATOS PERSONALES — para que Bell entienda ────────
    # "tengo 17", "tengo 25 años", "soy de Colombia"
    'tengo':        {'id': 'VERBO_TENER_YO_DATO', 'grounding': 0.85, 'tipo': 'dato_personal'},
    'tengo años':   {'id': 'DATO_EDAD',            'grounding': 0.95, 'tipo': 'dato_personal'},
    'años':         {'id': 'DATO_EDAD_UNIDAD',     'grounding': 0.85, 'tipo': 'dato_personal'},
    'soy de':       {'id': 'DATO_ORIGEN',          'grounding': 0.90, 'tipo': 'dato_personal'},
    'vivo en':      {'id': 'DATO_UBICACION',       'grounding': 0.90, 'tipo': 'dato_personal'},
    'me llamo':     {'id': 'DATO_NOMBRE',          'grounding': 0.95, 'tipo': 'dato_personal'},
    'mi nombre':    {'id': 'DATO_NOMBRE',          'grounding': 0.90, 'tipo': 'dato_personal'},
    'trabajo en':   {'id': 'DATO_TRABAJO',         'grounding': 0.90, 'tipo': 'dato_personal'},
    'estudio':      {'id': 'DATO_ESTUDIO',         'grounding': 0.85, 'tipo': 'dato_personal'},
    'estudio en':   {'id': 'DATO_ESTUDIO',         'grounding': 0.90, 'tipo': 'dato_personal'},

    # ── EXPRESIONES CONVERSACIONALES ─────────────────────
    # Las que más usa la gente al hablar
    'o sea':        {'id': 'EXPR_O_SEA',       'grounding': 0.85, 'tipo': 'conector_conversacional'},
    'osea':         {'id': 'EXPR_O_SEA',       'grounding': 0.85, 'tipo': 'conector_conversacional'},
    'es decir':     {'id': 'EXPR_ES_DECIR',    'grounding': 0.85, 'tipo': 'conector_conversacional'},
    'o sea que':    {'id': 'EXPR_O_SEA',       'grounding': 0.85, 'tipo': 'conector_conversacional'},
    'digamos':      {'id': 'EXPR_DIGAMOS',     'grounding': 0.80, 'tipo': 'conector_conversacional'},
    'o algo así':   {'id': 'EXPR_APROX',       'grounding': 0.80, 'tipo': 'aproximador'},
    'algo así':     {'id': 'EXPR_APROX',       'grounding': 0.80, 'tipo': 'aproximador'},
    'más o menos':  {'id': 'EXPR_MAS_O_MENOS', 'grounding': 0.85, 'tipo': 'aproximador'},
    'mas o menos':  {'id': 'EXPR_MAS_O_MENOS', 'grounding': 0.85, 'tipo': 'aproximador'},
    'tipo':         {'id': 'EXPR_APROX',       'grounding': 0.75, 'tipo': 'aproximador'},
    'como que':     {'id': 'EXPR_COMO_QUE',    'grounding': 0.80, 'tipo': 'conector_conversacional'},
    'de hecho':     {'id': 'EXPR_DE_HECHO',    'grounding': 0.85, 'tipo': 'enfatizador'},
    'en realidad':  {'id': 'EXPR_EN_REALIDAD', 'grounding': 0.85, 'tipo': 'enfatizador'},
    'la verdad':    {'id': 'EXPR_LA_VERDAD',   'grounding': 0.85, 'tipo': 'enfatizador'},
    'a ver':        {'id': 'EXPR_A_VER',       'grounding': 0.80, 'tipo': 'inicio_reflexion'},
    'bueno':        {'id': 'EXPR_BUENO',       'grounding': 0.80, 'tipo': 'inicio_reflexion'},
    'pues':         {'id': 'EXPR_PUES',        'grounding': 0.75, 'tipo': 'conector_conversacional'},
    'entonces':     {'id': 'EXPR_ENTONCES',    'grounding': 0.85, 'tipo': 'conector_causal'},
    'así que':      {'id': 'EXPR_ENTONCES',    'grounding': 0.85, 'tipo': 'conector_causal'},
    'ya':           {'id': 'EXPR_YA',          'grounding': 0.80, 'tipo': 'confirmacion_informal'},
    'ya sé':        {'id': 'EXPR_YA_SE',       'grounding': 0.85, 'tipo': 'conocimiento_previo'},
    'ya sabes':     {'id': 'EXPR_YA_SABES',    'grounding': 0.85, 'tipo': 'referencia_compartida'},
    'tú sabes':     {'id': 'EXPR_YA_SABES',    'grounding': 0.85, 'tipo': 'referencia_compartida'},
    'tu sabes':     {'id': 'EXPR_YA_SABES',    'grounding': 0.85, 'tipo': 'referencia_compartida'},
    'igual':        {'id': 'EXPR_IGUAL',       'grounding': 0.75, 'tipo': 'aproximador'},
    'literalmente': {'id': 'EXPR_LITERALMENTE','grounding': 0.80, 'tipo': 'enfatizador'},

    # ── EXPRESIONES DE ESTADO PERSONAL ───────────────────
    'no sé':        {'id': 'EXPR_NO_SE',       'grounding': 0.90, 'tipo': 'desconocimiento'},
    'no se':        {'id': 'EXPR_NO_SE',       'grounding': 0.85, 'tipo': 'desconocimiento'},
    'no sé qué':    {'id': 'EXPR_NO_SE',       'grounding': 0.90, 'tipo': 'desconocimiento'},
    'no entiendo':  {'id': 'EXPR_NO_ENTIENDO', 'grounding': 0.90, 'tipo': 'confusion'},
    'no entendí':   {'id': 'EXPR_NO_ENTIENDO', 'grounding': 0.90, 'tipo': 'confusion'},
    'no puedo':     {'id': 'EXPR_NO_PUEDO',    'grounding': 0.90, 'tipo': 'limitacion'},
    'no quiero':    {'id': 'EXPR_NO_QUIERO',   'grounding': 0.90, 'tipo': 'rechazo'},
    'no me gusta':  {'id': 'EXPR_NO_GUSTA',    'grounding': 0.90, 'tipo': 'preferencia'},
    'me gusta':     {'id': 'EXPR_ME_GUSTA',    'grounding': 0.90, 'tipo': 'preferencia'},
    'me encanta':   {'id': 'EXPR_ME_ENCANTA',  'grounding': 0.90, 'tipo': 'preferencia'},
    'odio':         {'id': 'EXPR_ODIO',        'grounding': 0.90, 'tipo': 'aversion'},
    'amo':          {'id': 'EXPR_AMO',         'grounding': 0.90, 'tipo': 'afecto'},
    'creo que':     {'id': 'EXPR_CREO_QUE',    'grounding': 0.85, 'tipo': 'opinion'},
    'pienso que':   {'id': 'EXPR_PIENSO_QUE',  'grounding': 0.85, 'tipo': 'opinion'},
    'siento que':   {'id': 'EXPR_SIENTO_QUE',  'grounding': 0.85, 'tipo': 'sentimiento'},
    'siento':       {'id': 'EXPR_SIENTO',      'grounding': 0.85, 'tipo': 'sentimiento'},
    'me siento':    {'id': 'EXPR_ME_SIENTO',   'grounding': 0.90, 'tipo': 'estado_emocional'},
    'quizás':       {'id': 'EXPR_QUIZAS',      'grounding': 0.85, 'tipo': 'incertidumbre'},
    'quizas':       {'id': 'EXPR_QUIZAS',      'grounding': 0.80, 'tipo': 'incertidumbre'},
    'tal vez':      {'id': 'EXPR_TAL_VEZ',     'grounding': 0.85, 'tipo': 'incertidumbre'},
    'a lo mejor':   {'id': 'EXPR_A_LO_MEJOR',  'grounding': 0.85, 'tipo': 'incertidumbre'},
    'espero':       {'id': 'EXPR_ESPERO',      'grounding': 0.85, 'tipo': 'deseo'},
    'ojalá':        {'id': 'EXPR_OJALA',       'grounding': 0.90, 'tipo': 'deseo'},
    'ojalá que':    {'id': 'EXPR_OJALA',       'grounding': 0.90, 'tipo': 'deseo'},

    # ── PETICIONES Y SOLICITUDES ──────────────────────────
    'por favor':    {'id': 'EXPR_POR_FAVOR',   'grounding': 0.90, 'tipo': 'cortesia'},
    'porfa':        {'id': 'EXPR_POR_FAVOR',   'grounding': 0.85, 'tipo': 'cortesia'},
    'porfavor':     {'id': 'EXPR_POR_FAVOR',   'grounding': 0.85, 'tipo': 'cortesia'},
    'necesito':     {'id': 'EXPR_NECESITO',    'grounding': 0.90, 'tipo': 'necesidad'},
    'necesito que': {'id': 'EXPR_NECESITO',    'grounding': 0.90, 'tipo': 'necesidad'},
    'quiero que':   {'id': 'EXPR_QUIERO_QUE',  'grounding': 0.90, 'tipo': 'deseo'},
    'ayúdame':      {'id': 'VERBO_AYUDAR_ME',  'grounding': 0.95, 'tipo': 'peticion'},
    'ayudame':      {'id': 'VERBO_AYUDAR_ME',  'grounding': 0.95, 'tipo': 'peticion'},
    'dime':         {'id': 'VERBO_DECIR_ME',   'grounding': 0.90, 'tipo': 'peticion'},
    'cuéntame':     {'id': 'VERBO_CONTAR_ME',  'grounding': 0.90, 'tipo': 'peticion'},
    'cuentame':     {'id': 'VERBO_CONTAR_ME',  'grounding': 0.90, 'tipo': 'peticion'},
    'explícame':    {'id': 'VERBO_EXPLICAR_ME','grounding': 0.90, 'tipo': 'peticion'},
    'explicame':    {'id': 'VERBO_EXPLICAR_ME','grounding': 0.90, 'tipo': 'peticion'},
    'muéstrame':    {'id': 'VERBO_MOSTRAR_ME', 'grounding': 0.90, 'tipo': 'peticion'},
    'muestrame':    {'id': 'VERBO_MOSTRAR_ME', 'grounding': 0.90, 'tipo': 'peticion'},

    # ── CONECTORES TEMPORALES ─────────────────────────────
    'antes':        {'id': 'TIEMPO_ANTES',     'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'después':      {'id': 'TIEMPO_DESPUES',   'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'despues':      {'id': 'TIEMPO_DESPUES',   'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'luego':        {'id': 'TIEMPO_DESPUES',   'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'ahora':        {'id': 'TIEMPO_AHORA',     'grounding': 0.90, 'tipo': 'tiempo_presente'},
    'ya':           {'id': 'TIEMPO_YA',        'grounding': 0.85, 'tipo': 'tiempo_completado'},
    'todavía':      {'id': 'TIEMPO_TODAVIA',   'grounding': 0.85, 'tipo': 'tiempo_continuo'},
    'todavia':      {'id': 'TIEMPO_TODAVIA',   'grounding': 0.85, 'tipo': 'tiempo_continuo'},
    'aún':          {'id': 'TIEMPO_TODAVIA',   'grounding': 0.85, 'tipo': 'tiempo_continuo'},
    'aun':          {'id': 'TIEMPO_TODAVIA',   'grounding': 0.80, 'tipo': 'tiempo_continuo'},
    'siempre':      {'id': 'TIEMPO_SIEMPRE',   'grounding': 0.90, 'tipo': 'tiempo_permanente'},
    'nunca':        {'id': 'TIEMPO_NUNCA',     'grounding': 0.90, 'tipo': 'tiempo_ausente'},

    # ── FRASES DE FRUSTRACIÓN / QUEJA ────────────────────
    'no funciona':      {'id': 'EXPR_NO_FUNCIONA',  'grounding': 0.90, 'tipo': 'queja'},
    'no sirve':         {'id': 'EXPR_NO_FUNCIONA',  'grounding': 0.90, 'tipo': 'queja'},
    'está mal':         {'id': 'EXPR_ESTA_MAL',     'grounding': 0.90, 'tipo': 'queja'},
    'no está bien':     {'id': 'EXPR_ESTA_MAL',     'grounding': 0.90, 'tipo': 'queja'},
    'no me entiendes':  {'id': 'EXPR_NO_ENTIENDE',  'grounding': 0.95, 'tipo': 'frustracion'},
    'no me entendiste': {'id': 'EXPR_NO_ENTIENDE',  'grounding': 0.95, 'tipo': 'frustracion'},
    'eso no es':        {'id': 'EXPR_NEGACION_DIRECTA','grounding': 0.90, 'tipo': 'negacion'},
    'no es así':        {'id': 'EXPR_NEGACION_DIRECTA','grounding': 0.90, 'tipo': 'negacion'},
    'no es eso':        {'id': 'EXPR_NEGACION_DIRECTA','grounding': 0.90, 'tipo': 'negacion'},

    # ── FRASES DE CONTINUACIÓN ────────────────────────────
    'sigue':        {'id': 'EXPR_CONTINUA',    'grounding': 0.85, 'tipo': 'continuacion'},
    'continúa':     {'id': 'EXPR_CONTINUA',    'grounding': 0.85, 'tipo': 'continuacion'},
    'continua':     {'id': 'EXPR_CONTINUA',    'grounding': 0.85, 'tipo': 'continuacion'},
    'y luego':      {'id': 'EXPR_CONTINUA',    'grounding': 0.80, 'tipo': 'continuacion'},
    'siguiente':    {'id': 'EXPR_SIGUIENTE',   'grounding': 0.85, 'tipo': 'continuacion'},
    'otro':         {'id': 'EXPR_OTRO',        'grounding': 0.75, 'tipo': 'alternativa'},
    'otra':         {'id': 'EXPR_OTRO',        'grounding': 0.75, 'tipo': 'alternativa'},
    'además':       {'id': 'EXPR_ADEMAS',      'grounding': 0.85, 'tipo': 'adicion'},
    'también':      {'id': 'EXPR_TAMBIEN',     'grounding': 0.85, 'tipo': 'adicion'},
    'tambien':      {'id': 'EXPR_TAMBIEN',     'grounding': 0.85, 'tipo': 'adicion'},

    # ── EXPRESIONES DE ACUERDO / DESACUERDO ──────────────
    'ok':           {'id': 'EXPR_OK',          'grounding': 0.90, 'tipo': 'confirmacion'},
    'okay':         {'id': 'EXPR_OK',          'grounding': 0.90, 'tipo': 'confirmacion'},
    'dale':         {'id': 'EXPR_DALE',        'grounding': 0.85, 'tipo': 'confirmacion'},
    'listo':        {'id': 'EXPR_LISTO',       'grounding': 0.85, 'tipo': 'confirmacion'},
    'perfecto':     {'id': 'EXPR_PERFECTO',    'grounding': 0.85, 'tipo': 'confirmacion'},
    'entendido':    {'id': 'EXPR_ENTENDIDO',   'grounding': 0.90, 'tipo': 'confirmacion'},
    'de acuerdo':   {'id': 'EXPR_DE_ACUERDO',  'grounding': 0.90, 'tipo': 'confirmacion'},
    'claro que sí': {'id': 'AFIRMACION_FUERTE','grounding': 0.95, 'tipo': 'confirmacion'},
    'por supuesto': {'id': 'AFIRMACION_FUERTE','grounding': 0.90, 'tipo': 'confirmacion'},
    'desde luego':  {'id': 'AFIRMACION_FUERTE','grounding': 0.90, 'tipo': 'confirmacion'},

    # ── PREGUNTAS SOBRE BELL — variantes naturales ────────
    'cuéntame de ti':    {'id': 'PREG_QUIEN_ES_BELL', 'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'cuentame de ti':    {'id': 'PREG_QUIEN_ES_BELL', 'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'dime sobre ti':     {'id': 'PREG_QUIEN_ES_BELL', 'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'háblame de ti':     {'id': 'PREG_QUIEN_ES_BELL', 'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'hablame de ti':     {'id': 'PREG_QUIEN_ES_BELL', 'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'eres consciente':   {'id': 'PREG_QUE_ES_BELL',   'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'tienes sentimientos':{'id': 'PREG_QUE_ES_BELL',  'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'eres una ia':       {'id': 'PREG_QUE_ES_BELL',   'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'eres robot':        {'id': 'PREG_QUE_ES_BELL',   'grounding': 0.90, 'tipo': 'pregunta_bell'},
    'eres un bot':       {'id': 'PREG_QUE_ES_BELL',   'grounding': 0.90, 'tipo': 'pregunta_bell'},
    'qué tipo de ia':    {'id': 'PREG_QUE_ES_BELL',   'grounding': 0.95, 'tipo': 'pregunta_bell'},
    'que tipo de ia':    {'id': 'PREG_QUE_ES_BELL',   'grounding': 0.95, 'tipo': 'pregunta_bell'},
}