# biblioteca/vocabulario/base/salud.py
SALUD = {
    'dolor':       {'id': 'SALUD_DOLOR',    'tipo': 'sintoma',    'grounding_base': 0.92, 'variantes': ['dolores', 'duele', 'me duele', 'doler']},
    'fiebre':      {'id': 'SALUD_FIEBRE',   'tipo': 'sintoma',    'grounding_base': 0.90, 'variantes': ['fiebres', 'temperatura', 'calentura']},
    'gripa':       {'id': 'SALUD_GRIPA',    'tipo': 'enfermedad', 'grounding_base': 0.90, 'variantes': ['gripe', 'catarro', 'resfriado', 'resfrío']},
    'enfermo':     {'id': 'SALUD_ENFERMO',  'tipo': 'estado_salud','grounding_base': 0.92,'variantes': ['enferma', 'enfermos', 'mala', 'malito']},
    'sano':        {'id': 'SALUD_SANO',     'tipo': 'estado_salud','grounding_base': 0.90,'variantes': ['sana', 'saludable', 'bien de salud']},
    'cansado':     {'id': 'SALUD_CANSADO',  'tipo': 'estado_fisico','grounding_base': 0.92,'variantes': ['cansada', 'agotado', 'agotada', 'rendido', 'muerto del cansancio']},
    'dormido':     {'id': 'SALUD_DORMIDO',  'tipo': 'estado_fisico','grounding_base': 0.88,'variantes': ['dormida', 'dormí', 'no dormí', 'sin dormir', 'desvelado']},
    'hambre':      {'id': 'SALUD_HAMBRE',   'tipo': 'necesidad_fisica','grounding_base': 0.92,'variantes': ['tengo hambre', 'hambriento', 'hambre']},
    'sed':         {'id': 'SALUD_SED',      'tipo': 'necesidad_fisica','grounding_base': 0.88,'variantes': ['tengo sed', 'sediento']},
    'médico':      {'id': 'SALUD_MEDICO',   'tipo': 'profesional_salud','grounding_base': 0.90,'variantes': ['doctor', 'doctora', 'médica', 'medico']},
    'pastilla':    {'id': 'SALUD_PASTILLA', 'tipo': 'medicamento', 'grounding_base': 0.88, 'variantes': ['pastillas', 'píldora', 'medicamento', 'medicina', 'droga']},
    'hospital':    {'id': 'SALUD_HOSPITAL', 'tipo': 'espacio_salud','grounding_base': 0.87,'variantes': ['hospitales', 'clínica', 'clinica', 'urgencias', 'emergencias']},
    'operación':   {'id': 'SALUD_OPERACION','tipo': 'procedimiento', 'grounding_base': 0.85,'variantes': ['operacion', 'cirugía', 'cirugia', 'operar']},
    'alergia':     {'id': 'SALUD_ALERGIA',  'tipo': 'enfermedad',  'grounding_base': 0.85, 'variantes': ['alergias', 'alérgico', 'alérgica']},
    'herida':      {'id': 'SALUD_HERIDA',   'tipo': 'lesion',      'grounding_base': 0.87, 'variantes': ['heridas', 'raspón', 'golpe', 'moretón']},
    'salud':       {'id': 'SALUD_CONCEPTO', 'tipo': 'concepto_salud','grounding_base': 0.90,'variantes': ['bienestar', 'condición física', 'estado de salud']},
    'ansiedad':    {'id': 'SALUD_ANSIEDAD', 'tipo': 'salud_mental', 'grounding_base': 0.90, 'variantes': ['ansioso', 'ansiosa', 'angustia', 'angustiado']},
    'depresión':   {'id': 'SALUD_DEPRESION','tipo': 'salud_mental', 'grounding_base': 0.90, 'variantes': ['depresion', 'deprimido', 'deprimida', 'estoy muy mal']},
    'estresado':   {'id': 'SALUD_ESTRES',   'tipo': 'salud_mental', 'grounding_base': 0.90, 'variantes': ['estrés', 'estres', 'estresada', 'al tope']},
    'dormir':      {'id': 'SALUD_DORMIR',   'tipo': 'necesidad_fisica','grounding_base': 0.92,'variantes': ['duermo', 'me voy a dormir', 'voy a dormir', 'buenas noches me voy']},
    'despertar':   {'id': 'SALUD_DESPERTAR','tipo': 'accion_fisica', 'grounding_base': 0.87,'variantes': ['me desperté', 'desperté', 'me levanté', 'ya me levanté']},
    'comer':       {'id': 'SALUD_COMER',    'tipo': 'necesidad_fisica','grounding_base': 0.92,'variantes': ['voy a comer', 'comiendo', 'comí', 'almorzar', 'desayunar', 'cenar']},
    'ejercicio':   {'id': 'SALUD_EJERCICIO','tipo': 'actividad_fisica','grounding_base': 0.87,'variantes': ['entrenar', 'entrenamiento', 'gym', 'correr']},
}
