# biblioteca/vocabulario/base/trabajo.py
TRABAJO = {
    'trabajo':      {'id': 'TRAB_TRABAJO',    'tipo': 'concepto_laboral', 'grounding_base': 0.93, 'variantes': ['trabajos', 'empleo', 'labor', 'laburo']},
    'trabajar':     {'id': 'TRAB_TRABAJAR',   'tipo': 'accion_laboral',   'grounding_base': 0.92, 'variantes': ['trabaja', 'trabajando', 'trabajé', 'laburar']},
    'jefe':         {'id': 'TRAB_JEFE',       'tipo': 'rol_laboral',      'grounding_base': 0.90, 'variantes': ['jefa', 'jefes', 'jefatura', 'superior']},
    'empresa':      {'id': 'TRAB_EMPRESA',    'tipo': 'entidad_laboral',  'grounding_base': 0.90, 'variantes': ['empresas', 'compañía', 'compania', 'negocio', 'organización']},
    'oficina':      {'id': 'TRAB_OFICINA',    'tipo': 'espacio_laboral',  'grounding_base': 0.88, 'variantes': ['oficinas', 'despacho']},
    'reunión':      {'id': 'TRAB_REUNION',    'tipo': 'evento_laboral',   'grounding_base': 0.90, 'variantes': ['reunion', 'reuniones', 'meeting', 'junta']},
    'proyecto':     {'id': 'TRAB_PROYECTO',   'tipo': 'tarea_laboral',    'grounding_base': 0.92, 'variantes': ['proyectos', 'proyecto de trabajo']},
    'sueldo':       {'id': 'TRAB_SUELDO',     'tipo': 'compensacion',     'grounding_base': 0.90, 'variantes': ['salario', 'paga', 'quincena', 'mensualidad']},
    'contrato':     {'id': 'TRAB_CONTRATO',   'tipo': 'documento_laboral','grounding_base': 0.87, 'variantes': ['contratos', 'acuerdo laboral']},
    'colega':       {'id': 'TRAB_COLEGA',     'tipo': 'relacion_laboral', 'grounding_base': 0.87, 'variantes': ['colegas', 'compañero de trabajo', 'compañeros']},
    'renunciar':    {'id': 'TRAB_RENUNCIAR',  'tipo': 'accion_laboral',   'grounding_base': 0.88, 'variantes': ['renuncia', 'dimisión', 'dimitir', 'irse del trabajo']},
    'contratar':    {'id': 'TRAB_CONTRATAR',  'tipo': 'accion_laboral',   'grounding_base': 0.87, 'variantes': ['contratación', 'contratado', 'conseguir trabajo']},
    'despedir':     {'id': 'TRAB_DESPEDIR',   'tipo': 'accion_laboral',   'grounding_base': 0.88, 'variantes': ['despido', 'despedido', 'echar del trabajo']},
    'tarea':        {'id': 'TRAB_TAREA',      'tipo': 'tarea_laboral',    'grounding_base': 0.88, 'variantes': ['tareas', 'pendiente', 'to-do']},
    'deadline':     {'id': 'TRAB_DEADLINE',   'tipo': 'evento_laboral',   'grounding_base': 0.87, 'variantes': ['fecha límite', 'fecha limite', 'entrega']},
    'presentación': {'id': 'TRAB_PRESENT',    'tipo': 'evento_laboral',   'grounding_base': 0.87, 'variantes': ['presentacion', 'expo', 'pitch']},
    'cliente':      {'id': 'TRAB_CLIENTE',    'tipo': 'relacion_laboral', 'grounding_base': 0.87, 'variantes': ['clientes', 'usuario', 'usuarios']},
    'profesional':  {'id': 'TRAB_PROFESIONAL','tipo': 'rol_laboral',      'grounding_base': 0.87, 'variantes': ['profesionales', 'experto', 'especialista']},
    'programador':  {'id': 'TRAB_PROGRAMADOR','tipo': 'profesion',        'grounding_base': 0.90, 'variantes': ['programadora', 'dev', 'developer', 'desarrollador', 'desarrolladora']},
    'diseñador':    {'id': 'TRAB_DISENADOR',  'tipo': 'profesion',        'grounding_base': 0.85, 'variantes': ['diseñadora', 'disenador', 'designer']},
    'médico':       {'id': 'TRAB_MEDICO',     'tipo': 'profesion',        'grounding_base': 0.87, 'variantes': ['medico', 'doctora', 'doctor', 'médica']},
    'abogado':      {'id': 'TRAB_ABOGADO',    'tipo': 'profesion',        'grounding_base': 0.85, 'variantes': ['abogada', 'abogados']},
    'me fue mal':   {'id': 'TRAB_MAL',        'tipo': 'evaluacion_laboral','grounding_base': 0.90,'variantes': ['salió mal', 'salió feo', 'pésimo en el trabajo']},
    'me fue bien':  {'id': 'TRAB_BIEN',       'tipo': 'evaluacion_laboral','grounding_base': 0.90,'variantes': ['salió bien', 'buen día de trabajo']},
    'estoy ocupado':{'id': 'TRAB_OCUPADO',    'tipo': 'estado_laboral',   'grounding_base': 0.88, 'variantes': ['sin tiempo', 'ocupadísimo', 'no puedo ahorita']},
}
