# biblioteca/vocabulario/base/verbos_comunes.py
# ================================================
# VERBOS Y EXPRESIONES — Vocabulario expandido
# Cubre ~80% del lenguaje natural en español
# Incluye: verbos conjugados, gerundios,
# participios, expresiones de tiempo y acción
# ================================================

VERBOS_COMUNES = {

    # ── ESTAR ────────────────────────────────────────────
    'estoy':          {'id': 'VERBO_ESTAR_YO',    'grounding': 0.85, 'tipo': 'verbo_estado'},
    'estás':          {'id': 'VERBO_ESTAR_TU',    'grounding': 0.85, 'tipo': 'verbo_estado'},
    'estas':          {'id': 'VERBO_ESTAR_TU',    'grounding': 0.85, 'tipo': 'verbo_estado'},
    'está':           {'id': 'VERBO_ESTAR_EL',    'grounding': 0.85, 'tipo': 'verbo_estado'},
    'esta':           {'id': 'VERBO_ESTAR_EL',    'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estamos':        {'id': 'VERBO_ESTAR_NOS',   'grounding': 0.85, 'tipo': 'verbo_estado'},
    'están':          {'id': 'VERBO_ESTAR_ELLOS', 'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estan':          {'id': 'VERBO_ESTAR_ELLOS', 'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estaba':         {'id': 'VERBO_ESTAR_PAS',   'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estabas':        {'id': 'VERBO_ESTAR_PAS',   'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estaré':         {'id': 'VERBO_ESTAR_FUT',   'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estarás':        {'id': 'VERBO_ESTAR_FUT',   'grounding': 0.80, 'tipo': 'verbo_estado'},
    'estando':        {'id': 'GERUNDIO_ESTAR',     'grounding': 0.80, 'tipo': 'gerundio'},

    # ── SER ──────────────────────────────────────────────
    'eres':           {'id': 'VERBO_SER_TU',      'grounding': 0.85, 'tipo': 'verbo_ser'},
    'es':             {'id': 'VERBO_SER_EL',      'grounding': 0.80, 'tipo': 'verbo_ser'},
    'somos':          {'id': 'VERBO_SER_NOS',     'grounding': 0.80, 'tipo': 'verbo_ser'},
    'soy':            {'id': 'VERBO_SER_YO',      'grounding': 0.85, 'tipo': 'verbo_ser'},
    'son':            {'id': 'VERBO_SER_ELLOS',   'grounding': 0.80, 'tipo': 'verbo_ser'},
    'era':            {'id': 'VERBO_SER_PAS',     'grounding': 0.80, 'tipo': 'verbo_ser'},
    'eras':           {'id': 'VERBO_SER_PAS',     'grounding': 0.80, 'tipo': 'verbo_ser'},
    'siendo':         {'id': 'GERUNDIO_SER',      'grounding': 0.80, 'tipo': 'gerundio'},
    'sido':           {'id': 'PART_SER',          'grounding': 0.75, 'tipo': 'participio'},
    'fue':            {'id': 'VERBO_SER_PAS3',    'grounding': 0.80, 'tipo': 'verbo_ser'},
    'fui':            {'id': 'VERBO_SER_PAS1',    'grounding': 0.80, 'tipo': 'verbo_ser'},
    'serás':          {'id': 'VERBO_SER_FUT',     'grounding': 0.80, 'tipo': 'verbo_ser'},
    'será':           {'id': 'VERBO_SER_FUT3',    'grounding': 0.80, 'tipo': 'verbo_ser'},

    # ── TENER ────────────────────────────────────────────
    'tengo':          {'id': 'VERBO_TENER_YO',    'grounding': 0.85, 'tipo': 'verbo_tener'},
    'tienes':         {'id': 'VERBO_TENER_TU',    'grounding': 0.85, 'tipo': 'verbo_tener'},
    'tiene':          {'id': 'VERBO_TENER_EL',    'grounding': 0.80, 'tipo': 'verbo_tener'},
    'tenemos':        {'id': 'VERBO_TENER_NOS',   'grounding': 0.80, 'tipo': 'verbo_tener'},
    'tienen':         {'id': 'VERBO_TENER_ELLOS', 'grounding': 0.80, 'tipo': 'verbo_tener'},
    'tenía':          {'id': 'VERBO_TENER_PAS',   'grounding': 0.75, 'tipo': 'verbo_tener'},
    'tenías':         {'id': 'VERBO_TENER_PAS',   'grounding': 0.75, 'tipo': 'verbo_tener'},
    'teniendo':       {'id': 'GERUNDIO_TENER',    'grounding': 0.80, 'tipo': 'gerundio'},
    'tenido':         {'id': 'PART_TENER',        'grounding': 0.75, 'tipo': 'participio'},
    'tendrás':        {'id': 'VERBO_TENER_FUT',   'grounding': 0.80, 'tipo': 'verbo_tener'},
    'tendré':         {'id': 'VERBO_TENER_FUT1',  'grounding': 0.80, 'tipo': 'verbo_tener'},

    # ── PODER ────────────────────────────────────────────
    'puedo':          {'id': 'VERBO_PODER_YO',    'grounding': 0.90, 'tipo': 'verbo_capacidad'},
    'puedes':         {'id': 'VERBO_PODER_TU',    'grounding': 0.90, 'tipo': 'verbo_capacidad'},
    'puede':          {'id': 'VERBO_PODER_EL',    'grounding': 0.85, 'tipo': 'verbo_capacidad'},
    'podemos':        {'id': 'VERBO_PODER_NOS',   'grounding': 0.85, 'tipo': 'verbo_capacidad'},
    'pueden':         {'id': 'VERBO_PODER_ELLOS', 'grounding': 0.85, 'tipo': 'verbo_capacidad'},
    'podía':          {'id': 'VERBO_PODER_PAS',   'grounding': 0.80, 'tipo': 'verbo_capacidad'},
    'podías':         {'id': 'VERBO_PODER_PAS',   'grounding': 0.80, 'tipo': 'verbo_capacidad'},
    'podré':          {'id': 'VERBO_PODER_FUT',   'grounding': 0.80, 'tipo': 'verbo_capacidad'},
    'podrás':         {'id': 'VERBO_PODER_FUT',   'grounding': 0.80, 'tipo': 'verbo_capacidad'},
    'pudiste':        {'id': 'VERBO_PODER_PAS2',  'grounding': 0.80, 'tipo': 'verbo_capacidad'},
    'pude':           {'id': 'VERBO_PODER_PAS1',  'grounding': 0.80, 'tipo': 'verbo_capacidad'},
    'pudiendo':       {'id': 'GERUNDIO_PODER',    'grounding': 0.80, 'tipo': 'gerundio'},

    # ── HACER ────────────────────────────────────────────
    'hago':           {'id': 'VERBO_HACER_YO',    'grounding': 0.85, 'tipo': 'verbo_accion'},
    'haces':          {'id': 'VERBO_HACER_TU',    'grounding': 0.85, 'tipo': 'verbo_accion'},
    'hace':           {'id': 'VERBO_HACER_EL',    'grounding': 0.80, 'tipo': 'verbo_accion'},
    'hacemos':        {'id': 'VERBO_HACER_NOS',   'grounding': 0.80, 'tipo': 'verbo_accion'},
    'hacen':          {'id': 'VERBO_HACER_ELLOS', 'grounding': 0.80, 'tipo': 'verbo_accion'},
    'hacer':          {'id': 'VERBO_HACER',       'grounding': 0.85, 'tipo': 'verbo_accion'},
    'haciendo':       {'id': 'GERUNDIO_HACER',    'grounding': 0.85, 'tipo': 'gerundio'},
    'hecho':          {'id': 'PART_HACER',        'grounding': 0.80, 'tipo': 'participio'},
    'hacía':          {'id': 'VERBO_HACER_PAS',   'grounding': 0.75, 'tipo': 'verbo_accion'},
    'hacías':         {'id': 'VERBO_HACER_PAS',   'grounding': 0.75, 'tipo': 'verbo_accion'},
    'hice':           {'id': 'VERBO_HACER_PAS1',  'grounding': 0.80, 'tipo': 'verbo_accion'},
    'hiciste':        {'id': 'VERBO_HACER_PAS2',  'grounding': 0.80, 'tipo': 'verbo_accion'},
    'haré':           {'id': 'VERBO_HACER_FUT',   'grounding': 0.80, 'tipo': 'verbo_accion'},
    'harás':          {'id': 'VERBO_HACER_FUT',   'grounding': 0.80, 'tipo': 'verbo_accion'},

    # ── QUERER ───────────────────────────────────────────
    'quiero':         {'id': 'VERBO_QUERER_YO',   'grounding': 0.90, 'tipo': 'verbo_deseo'},
    'quieres':        {'id': 'VERBO_QUERER_TU',   'grounding': 0.90, 'tipo': 'verbo_deseo'},
    'quiere':         {'id': 'VERBO_QUERER_EL',   'grounding': 0.85, 'tipo': 'verbo_deseo'},
    'queremos':       {'id': 'VERBO_QUERER_NOS',  'grounding': 0.85, 'tipo': 'verbo_deseo'},
    'quería':         {'id': 'VERBO_QUERER_PAS',  'grounding': 0.80, 'tipo': 'verbo_deseo'},
    'querías':        {'id': 'VERBO_QUERER_PAS',  'grounding': 0.80, 'tipo': 'verbo_deseo'},
    'queriendo':      {'id': 'GERUNDIO_QUERER',   'grounding': 0.80, 'tipo': 'gerundio'},
    'querido':        {'id': 'PART_QUERER',       'grounding': 0.80, 'tipo': 'participio'},
    'quisiera':       {'id': 'VERBO_QUERER_SUB',  'grounding': 0.85, 'tipo': 'verbo_deseo'},
    'quisieras':      {'id': 'VERBO_QUERER_SUB',  'grounding': 0.85, 'tipo': 'verbo_deseo'},

    # ── NECESITAR ────────────────────────────────────────
    'necesito':       {'id': 'VERBO_NECESITAR_YO','grounding': 0.90, 'tipo': 'verbo_necesidad'},
    'necesitas':      {'id': 'VERBO_NECESITAR_TU','grounding': 0.90, 'tipo': 'verbo_necesidad'},
    'necesita':       {'id': 'VERBO_NECESITAR_EL','grounding': 0.85, 'tipo': 'verbo_necesidad'},
    'necesitamos':    {'id': 'VERBO_NECESITAR_NOS','grounding': 0.85, 'tipo': 'verbo_necesidad'},
    'necesitaba':     {'id': 'VERBO_NECESITAR_PAS','grounding': 0.80, 'tipo': 'verbo_necesidad'},
    'necesitabas':    {'id': 'VERBO_NECESITAR_PAS','grounding': 0.80, 'tipo': 'verbo_necesidad'},
    'necesitando':    {'id': 'GERUNDIO_NECESITAR','grounding': 0.80, 'tipo': 'gerundio'},

    # ── SABER ────────────────────────────────────────────
    'sé':             {'id': 'VERBO_SABER_YO',    'grounding': 0.85, 'tipo': 'verbo_conocimiento'},
    'sabes':          {'id': 'VERBO_SABER_TU',    'grounding': 0.85, 'tipo': 'verbo_conocimiento'},
    'sabe':           {'id': 'VERBO_SABER_EL',    'grounding': 0.80, 'tipo': 'verbo_conocimiento'},
    'sabemos':        {'id': 'VERBO_SABER_NOS',   'grounding': 0.80, 'tipo': 'verbo_conocimiento'},
    'saben':          {'id': 'VERBO_SABER_ELLOS', 'grounding': 0.80, 'tipo': 'verbo_conocimiento'},
    'sabía':          {'id': 'VERBO_SABER_PAS',   'grounding': 0.75, 'tipo': 'verbo_conocimiento'},
    'sabías':         {'id': 'VERBO_SABER_PAS',   'grounding': 0.75, 'tipo': 'verbo_conocimiento'},
    'sabiendo':       {'id': 'GERUNDIO_SABER',    'grounding': 0.80, 'tipo': 'gerundio'},
    'sabido':         {'id': 'PART_SABER',        'grounding': 0.75, 'tipo': 'participio'},
    'supo':           {'id': 'VERBO_SABER_PAS3',  'grounding': 0.75, 'tipo': 'verbo_conocimiento'},

    # ── CONOCER / ENTENDER ────────────────────────────────
    'conozco':        {'id': 'VERBO_CONOCER_YO',  'grounding': 0.85, 'tipo': 'verbo_conocimiento'},
    'conoces':        {'id': 'VERBO_CONOCER_TU',  'grounding': 0.85, 'tipo': 'verbo_conocimiento'},
    'conoce':         {'id': 'VERBO_CONOCER_EL',  'grounding': 0.80, 'tipo': 'verbo_conocimiento'},
    'conocer':        {'id': 'VERBO_CONOCER',     'grounding': 0.85, 'tipo': 'verbo_conocimiento'},
    'conociendo':     {'id': 'GERUNDIO_CONOCER',  'grounding': 0.80, 'tipo': 'gerundio'},
    'conocido':       {'id': 'PART_CONOCER',      'grounding': 0.75, 'tipo': 'participio'},
    'entiendo':       {'id': 'VERBO_ENTENDER_YO', 'grounding': 0.85, 'tipo': 'verbo_comprension'},
    'entiendes':      {'id': 'VERBO_ENTENDER_TU', 'grounding': 0.85, 'tipo': 'verbo_comprension'},
    'entiende':       {'id': 'VERBO_ENTENDER_EL', 'grounding': 0.80, 'tipo': 'verbo_comprension'},
    'entendemos':     {'id': 'VERBO_ENTENDER_NOS','grounding': 0.80, 'tipo': 'verbo_comprension'},
    'entender':       {'id': 'VERBO_ENTENDER',    'grounding': 0.85, 'tipo': 'verbo_comprension'},
    'entendiendo':    {'id': 'GERUNDIO_ENTENDER', 'grounding': 0.85, 'tipo': 'gerundio'},
    'entendido':      {'id': 'PART_ENTENDER',     'grounding': 0.80, 'tipo': 'participio'},
    'entendí':        {'id': 'VERBO_ENTENDER_PAS','grounding': 0.80, 'tipo': 'verbo_comprension'},
    'entendiste':     {'id': 'VERBO_ENTENDER_PAS2','grounding': 0.80, 'tipo': 'verbo_comprension'},

    # ── HABLAR / DECIR ───────────────────────────────────
    'digo':           {'id': 'VERBO_DECIR_YO',    'grounding': 0.85, 'tipo': 'verbo_comunicacion'},
    'dices':          {'id': 'VERBO_DECIR_TU',    'grounding': 0.85, 'tipo': 'verbo_comunicacion'},
    'dice':           {'id': 'VERBO_DECIR_EL',    'grounding': 0.80, 'tipo': 'verbo_comunicacion'},
    'decir':          {'id': 'VERBO_DECIR',       'grounding': 0.85, 'tipo': 'verbo_comunicacion'},
    'diciendo':       {'id': 'GERUNDIO_DECIR',    'grounding': 0.85, 'tipo': 'gerundio'},
    'dicho':          {'id': 'PART_DECIR',        'grounding': 0.80, 'tipo': 'participio'},
    'dije':           {'id': 'VERBO_DECIR_PAS1',  'grounding': 0.80, 'tipo': 'verbo_comunicacion'},
    'dijiste':        {'id': 'VERBO_DECIR_PAS2',  'grounding': 0.80, 'tipo': 'verbo_comunicacion'},
    'hablo':          {'id': 'VERBO_HABLAR_YO',   'grounding': 0.85, 'tipo': 'verbo_comunicacion'},
    'hablas':         {'id': 'VERBO_HABLAR_TU',   'grounding': 0.85, 'tipo': 'verbo_comunicacion'},
    'habla':          {'id': 'VERBO_HABLAR_EL',   'grounding': 0.80, 'tipo': 'verbo_comunicacion'},
    'hablar':         {'id': 'VERBO_HABLAR',      'grounding': 0.85, 'tipo': 'verbo_comunicacion'},
    'hablando':       {'id': 'GERUNDIO_HABLAR',   'grounding': 0.85, 'tipo': 'gerundio'},
    'hablado':        {'id': 'PART_HABLAR',       'grounding': 0.75, 'tipo': 'participio'},
    'hablé':          {'id': 'VERBO_HABLAR_PAS',  'grounding': 0.80, 'tipo': 'verbo_comunicacion'},
    'hablaste':       {'id': 'VERBO_HABLAR_PAS2', 'grounding': 0.80, 'tipo': 'verbo_comunicacion'},
    'escucho':        {'id': 'VERBO_ESCUCHAR_YO', 'grounding': 0.85, 'tipo': 'verbo_percepcion'},
    'escuchas':       {'id': 'VERBO_ESCUCHAR_TU', 'grounding': 0.85, 'tipo': 'verbo_percepcion'},
    'escucha':        {'id': 'VERBO_ESCUCHAR_EL', 'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'escuchar':       {'id': 'VERBO_ESCUCHAR',    'grounding': 0.85, 'tipo': 'verbo_percepcion'},
    'escuchando':     {'id': 'GERUNDIO_ESCUCHAR', 'grounding': 0.85, 'tipo': 'gerundio'},
    'escuchado':      {'id': 'PART_ESCUCHAR',     'grounding': 0.75, 'tipo': 'participio'},

    # ── PENSAR / SENTIR / CREER ──────────────────────────
    'pienso':         {'id': 'VERBO_PENSAR_YO',   'grounding': 0.85, 'tipo': 'verbo_pensamiento'},
    'piensas':        {'id': 'VERBO_PENSAR_TU',   'grounding': 0.85, 'tipo': 'verbo_pensamiento'},
    'piensa':         {'id': 'VERBO_PENSAR_EL',   'grounding': 0.80, 'tipo': 'verbo_pensamiento'},
    'pensar':         {'id': 'VERBO_PENSAR',      'grounding': 0.85, 'tipo': 'verbo_pensamiento'},
    'pensando':       {'id': 'GERUNDIO_PENSAR',   'grounding': 0.85, 'tipo': 'gerundio'},
    'pensado':        {'id': 'PART_PENSAR',       'grounding': 0.75, 'tipo': 'participio'},
    'pensé':          {'id': 'VERBO_PENSAR_PAS',  'grounding': 0.80, 'tipo': 'verbo_pensamiento'},
    'pensaste':       {'id': 'VERBO_PENSAR_PAS2', 'grounding': 0.80, 'tipo': 'verbo_pensamiento'},
    'siento':         {'id': 'VERBO_SENTIR_YO',   'grounding': 0.90, 'tipo': 'verbo_emocion'},
    'sientes':        {'id': 'VERBO_SENTIR_TU',   'grounding': 0.90, 'tipo': 'verbo_emocion'},
    'siente':         {'id': 'VERBO_SENTIR_EL',   'grounding': 0.85, 'tipo': 'verbo_emocion'},
    'sentir':         {'id': 'VERBO_SENTIR',      'grounding': 0.85, 'tipo': 'verbo_emocion'},
    'sintiendo':      {'id': 'GERUNDIO_SENTIR',   'grounding': 0.85, 'tipo': 'gerundio'},
    'sentido':        {'id': 'PART_SENTIR',       'grounding': 0.80, 'tipo': 'participio'},
    'sentí':          {'id': 'VERBO_SENTIR_PAS',  'grounding': 0.80, 'tipo': 'verbo_emocion'},
    'sentiste':       {'id': 'VERBO_SENTIR_PAS2', 'grounding': 0.80, 'tipo': 'verbo_emocion'},
    'creo':           {'id': 'VERBO_CREER_YO',    'grounding': 0.85, 'tipo': 'verbo_pensamiento'},
    'crees':          {'id': 'VERBO_CREER_TU',    'grounding': 0.85, 'tipo': 'verbo_pensamiento'},
    'cree':           {'id': 'VERBO_CREER_EL',    'grounding': 0.80, 'tipo': 'verbo_pensamiento'},
    'creer':          {'id': 'VERBO_CREER',       'grounding': 0.85, 'tipo': 'verbo_pensamiento'},
    'creyendo':       {'id': 'GERUNDIO_CREER',    'grounding': 0.80, 'tipo': 'gerundio'},
    'creído':         {'id': 'PART_CREER',        'grounding': 0.75, 'tipo': 'participio'},
    'creí':           {'id': 'VERBO_CREER_PAS',   'grounding': 0.75, 'tipo': 'verbo_pensamiento'},

    # ── IR / VENIR ───────────────────────────────────────
    'voy':            {'id': 'VERBO_IR_YO',       'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'vas':            {'id': 'VERBO_IR_TU',       'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'va':             {'id': 'VERBO_IR_EL',       'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'vamos':          {'id': 'VERBO_IR_NOS',      'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'van':            {'id': 'VERBO_IR_ELLOS',    'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'ir':             {'id': 'VERBO_IR',          'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'yendo':          {'id': 'GERUNDIO_IR',       'grounding': 0.80, 'tipo': 'gerundio'},
    'ido':            {'id': 'PART_IR',           'grounding': 0.75, 'tipo': 'participio'},
    'fui':            {'id': 'VERBO_IR_PAS1',     'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'fuiste':         {'id': 'VERBO_IR_PAS2',     'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'iré':            {'id': 'VERBO_IR_FUT',      'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'irás':           {'id': 'VERBO_IR_FUT',      'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'vengo':          {'id': 'VERBO_VENIR_YO',    'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'vienes':         {'id': 'VERBO_VENIR_TU',    'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'viene':          {'id': 'VERBO_VENIR_EL',    'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'venimos':        {'id': 'VERBO_VENIR_NOS',   'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'venir':          {'id': 'VERBO_VENIR',       'grounding': 0.85, 'tipo': 'verbo_movimiento'},
    'viniendo':       {'id': 'GERUNDIO_VENIR',    'grounding': 0.80, 'tipo': 'gerundio'},
    'venido':         {'id': 'PART_VENIR',        'grounding': 0.75, 'tipo': 'participio'},
    'vine':           {'id': 'VERBO_VENIR_PAS',   'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'viniste':        {'id': 'VERBO_VENIR_PAS2',  'grounding': 0.80, 'tipo': 'verbo_movimiento'},

    # ── DAR / TOMAR ──────────────────────────────────────
    'doy':            {'id': 'VERBO_DAR_YO',      'grounding': 0.85, 'tipo': 'verbo_accion'},
    'das':            {'id': 'VERBO_DAR_TU',      'grounding': 0.85, 'tipo': 'verbo_accion'},
    'da':             {'id': 'VERBO_DAR_EL',      'grounding': 0.80, 'tipo': 'verbo_accion'},
    'dar':            {'id': 'VERBO_DAR',         'grounding': 0.85, 'tipo': 'verbo_accion'},
    'dando':          {'id': 'GERUNDIO_DAR',      'grounding': 0.80, 'tipo': 'gerundio'},
    'dado':           {'id': 'PART_DAR',          'grounding': 0.75, 'tipo': 'participio'},
    'di':             {'id': 'VERBO_DAR_PAS',     'grounding': 0.75, 'tipo': 'verbo_accion'},
    'diste':          {'id': 'VERBO_DAR_PAS2',    'grounding': 0.75, 'tipo': 'verbo_accion'},
    'tomo':           {'id': 'VERBO_TOMAR_YO',    'grounding': 0.80, 'tipo': 'verbo_accion'},
    'tomas':          {'id': 'VERBO_TOMAR_TU',    'grounding': 0.80, 'tipo': 'verbo_accion'},
    'toma':           {'id': 'VERBO_TOMAR_EL',    'grounding': 0.75, 'tipo': 'verbo_accion'},
    'tomar':          {'id': 'VERBO_TOMAR',       'grounding': 0.80, 'tipo': 'verbo_accion'},
    'tomando':        {'id': 'GERUNDIO_TOMAR',    'grounding': 0.80, 'tipo': 'gerundio'},
    'tomado':         {'id': 'PART_TOMAR',        'grounding': 0.75, 'tipo': 'participio'},

    # ── AYUDAR ───────────────────────────────────────────
    'ayudo':          {'id': 'VERBO_AYUDAR_YO',   'grounding': 0.90, 'tipo': 'verbo_ayuda'},
    'ayudas':         {'id': 'VERBO_AYUDAR_TU',   'grounding': 0.90, 'tipo': 'verbo_ayuda'},
    'ayuda':          {'id': 'VERBO_AYUDA',       'grounding': 0.90, 'tipo': 'verbo_ayuda'},
    'ayudar':         {'id': 'VERBO_AYUDAR',      'grounding': 0.90, 'tipo': 'verbo_ayuda'},
    'ayudando':       {'id': 'GERUNDIO_AYUDAR',   'grounding': 0.85, 'tipo': 'gerundio'},
    'ayudado':        {'id': 'PART_AYUDAR',       'grounding': 0.80, 'tipo': 'participio'},
    'ayúdame':        {'id': 'VERBO_AYUDAR_ME',   'grounding': 0.95, 'tipo': 'peticion'},
    'ayudame':        {'id': 'VERBO_AYUDAR_ME',   'grounding': 0.95, 'tipo': 'peticion'},
    'ayudé':          {'id': 'VERBO_AYUDAR_PAS',  'grounding': 0.80, 'tipo': 'verbo_ayuda'},
    'ayudaste':       {'id': 'VERBO_AYUDAR_PAS2', 'grounding': 0.80, 'tipo': 'verbo_ayuda'},

    # ── TRABAJAR / APRENDER ──────────────────────────────
    'trabajo':        {'id': 'VERBO_TRABAJAR_YO', 'grounding': 0.85, 'tipo': 'verbo_trabajo'},
    'trabajas':       {'id': 'VERBO_TRABAJAR_TU', 'grounding': 0.85, 'tipo': 'verbo_trabajo'},
    'trabaja':        {'id': 'VERBO_TRABAJAR_EL', 'grounding': 0.80, 'tipo': 'verbo_trabajo'},
    'trabajar':       {'id': 'VERBO_TRABAJAR',    'grounding': 0.85, 'tipo': 'verbo_trabajo'},
    'trabajando':     {'id': 'GERUNDIO_TRABAJAR', 'grounding': 0.85, 'tipo': 'gerundio'},
    'trabajado':      {'id': 'PART_TRABAJAR',     'grounding': 0.75, 'tipo': 'participio'},
    'trabajé':        {'id': 'VERBO_TRABAJAR_PAS','grounding': 0.80, 'tipo': 'verbo_trabajo'},
    'trabajaste':     {'id': 'VERBO_TRABAJAR_PAS2','grounding': 0.80, 'tipo': 'verbo_trabajo'},
    'aprendo':        {'id': 'VERBO_APRENDER_YO', 'grounding': 0.90, 'tipo': 'verbo_aprendizaje'},
    'aprendes':       {'id': 'VERBO_APRENDER_TU', 'grounding': 0.90, 'tipo': 'verbo_aprendizaje'},
    'aprende':        {'id': 'VERBO_APRENDER_EL', 'grounding': 0.85, 'tipo': 'verbo_aprendizaje'},
    'aprender':       {'id': 'VERBO_APRENDER',    'grounding': 0.90, 'tipo': 'verbo_aprendizaje'},
    'aprendiendo':    {'id': 'GERUNDIO_APRENDER', 'grounding': 0.90, 'tipo': 'gerundio'},
    'aprendido':      {'id': 'PART_APRENDER',     'grounding': 0.85, 'tipo': 'participio'},
    'aprendí':        {'id': 'VERBO_APRENDER_PAS','grounding': 0.85, 'tipo': 'verbo_aprendizaje'},
    'aprendiste':     {'id': 'VERBO_APRENDER_PAS2','grounding': 0.85, 'tipo': 'verbo_aprendizaje'},

    # ── PROCESAR / ANALIZAR / CREAR ──────────────────────
    'proceso':        {'id': 'VERBO_PROCESAR_YO', 'grounding': 0.85, 'tipo': 'verbo_accion'},
    'procesas':       {'id': 'VERBO_PROCESAR_TU', 'grounding': 0.85, 'tipo': 'verbo_accion'},
    'procesa':        {'id': 'VERBO_PROCESAR_EL', 'grounding': 0.80, 'tipo': 'verbo_accion'},
    'procesar':       {'id': 'VERBO_PROCESAR',    'grounding': 0.85, 'tipo': 'verbo_accion'},
    'procesando':     {'id': 'GERUNDIO_PROCESAR', 'grounding': 0.85, 'tipo': 'gerundio'},
    'procesado':      {'id': 'PART_PROCESAR',     'grounding': 0.80, 'tipo': 'participio'},
    'analizo':        {'id': 'VERBO_ANALIZAR_YO', 'grounding': 0.85, 'tipo': 'verbo_accion'},
    'analizas':       {'id': 'VERBO_ANALIZAR_TU', 'grounding': 0.85, 'tipo': 'verbo_accion'},
    'analiza':        {'id': 'VERBO_ANALIZAR_EL', 'grounding': 0.80, 'tipo': 'verbo_accion'},
    'analizar':       {'id': 'VERBO_ANALIZAR',    'grounding': 0.85, 'tipo': 'verbo_accion'},
    'analizando':     {'id': 'GERUNDIO_ANALIZAR', 'grounding': 0.85, 'tipo': 'gerundio'},
    'analizado':      {'id': 'PART_ANALIZAR',     'grounding': 0.80, 'tipo': 'participio'},
    'creo':           {'id': 'VERBO_CREAR_YO',    'grounding': 0.85, 'tipo': 'verbo_creacion'},
    'creas':          {'id': 'VERBO_CREAR_TU',    'grounding': 0.85, 'tipo': 'verbo_creacion'},
    'crea':           {'id': 'VERBO_CREAR_EL',    'grounding': 0.80, 'tipo': 'verbo_creacion'},
    'crear':          {'id': 'VERBO_CREAR',       'grounding': 0.85, 'tipo': 'verbo_creacion'},
    'creando':        {'id': 'GERUNDIO_CREAR',    'grounding': 0.85, 'tipo': 'gerundio'},
    'creado':         {'id': 'PART_CREAR',        'grounding': 0.80, 'tipo': 'participio'},
    'construyo':      {'id': 'VERBO_CONSTRUIR_YO','grounding': 0.85, 'tipo': 'verbo_creacion'},
    'construyes':     {'id': 'VERBO_CONSTRUIR_TU','grounding': 0.85, 'tipo': 'verbo_creacion'},
    'construye':      {'id': 'VERBO_CONSTRUIR_EL','grounding': 0.80, 'tipo': 'verbo_creacion'},
    'construir':      {'id': 'VERBO_CONSTRUIR',   'grounding': 0.85, 'tipo': 'verbo_creacion'},
    'construyendo':   {'id': 'GERUNDIO_CONSTRUIR','grounding': 0.85, 'tipo': 'gerundio'},
    'construido':     {'id': 'PART_CONSTRUIR',    'grounding': 0.80, 'tipo': 'participio'},

    # ── VER / MIRAR / BUSCAR ─────────────────────────────
    'veo':            {'id': 'VERBO_VER_YO',      'grounding': 0.85, 'tipo': 'verbo_percepcion'},
    'ves':            {'id': 'VERBO_VER_TU',      'grounding': 0.85, 'tipo': 'verbo_percepcion'},
    've':             {'id': 'VERBO_VER_EL',      'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'ver':            {'id': 'VERBO_VER',         'grounding': 0.85, 'tipo': 'verbo_percepcion'},
    'viendo':         {'id': 'GERUNDIO_VER',      'grounding': 0.80, 'tipo': 'gerundio'},
    'visto':          {'id': 'PART_VER',          'grounding': 0.80, 'tipo': 'participio'},
    'vi':             {'id': 'VERBO_VER_PAS',     'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'viste':          {'id': 'VERBO_VER_PAS2',    'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'miro':           {'id': 'VERBO_MIRAR_YO',    'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'miras':          {'id': 'VERBO_MIRAR_TU',    'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'mira':           {'id': 'VERBO_MIRAR_EL',    'grounding': 0.75, 'tipo': 'verbo_percepcion'},
    'mirar':          {'id': 'VERBO_MIRAR',       'grounding': 0.80, 'tipo': 'verbo_percepcion'},
    'mirando':        {'id': 'GERUNDIO_MIRAR',    'grounding': 0.80, 'tipo': 'gerundio'},
    'busco':          {'id': 'VERBO_BUSCAR_YO',   'grounding': 0.85, 'tipo': 'verbo_accion'},
    'buscas':         {'id': 'VERBO_BUSCAR_TU',   'grounding': 0.85, 'tipo': 'verbo_accion'},
    'busca':          {'id': 'VERBO_BUSCAR_EL',   'grounding': 0.80, 'tipo': 'verbo_accion'},
    'buscar':         {'id': 'VERBO_BUSCAR',      'grounding': 0.85, 'tipo': 'verbo_accion'},
    'buscando':       {'id': 'GERUNDIO_BUSCAR',   'grounding': 0.85, 'tipo': 'gerundio'},
    'buscado':        {'id': 'PART_BUSCAR',       'grounding': 0.75, 'tipo': 'participio'},

    # ── LLEGAR / EMPEZAR / TERMINAR ──────────────────────
    'llego':          {'id': 'VERBO_LLEGAR_YO',   'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'llegas':         {'id': 'VERBO_LLEGAR_TU',   'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'llega':          {'id': 'VERBO_LLEGAR_EL',   'grounding': 0.75, 'tipo': 'verbo_movimiento'},
    'llegar':         {'id': 'VERBO_LLEGAR',      'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'llegando':       {'id': 'GERUNDIO_LLEGAR',   'grounding': 0.80, 'tipo': 'gerundio'},
    'llegado':        {'id': 'PART_LLEGAR',       'grounding': 0.75, 'tipo': 'participio'},
    'llegué':         {'id': 'VERBO_LLEGAR_PAS',  'grounding': 0.80, 'tipo': 'verbo_movimiento'},
    'empiezo':        {'id': 'VERBO_EMPEZAR_YO',  'grounding': 0.85, 'tipo': 'verbo_inicio'},
    'empiezas':       {'id': 'VERBO_EMPEZAR_TU',  'grounding': 0.85, 'tipo': 'verbo_inicio'},
    'empieza':        {'id': 'VERBO_EMPEZAR_EL',  'grounding': 0.80, 'tipo': 'verbo_inicio'},
    'empezar':        {'id': 'VERBO_EMPEZAR',     'grounding': 0.85, 'tipo': 'verbo_inicio'},
    'empezando':      {'id': 'GERUNDIO_EMPEZAR',  'grounding': 0.85, 'tipo': 'gerundio'},
    'empezado':       {'id': 'PART_EMPEZAR',      'grounding': 0.80, 'tipo': 'participio'},
    'empecé':         {'id': 'VERBO_EMPEZAR_PAS', 'grounding': 0.80, 'tipo': 'verbo_inicio'},
    'inicio':         {'id': 'VERBO_INICIAR_YO',  'grounding': 0.80, 'tipo': 'verbo_inicio'},
    'termino':        {'id': 'VERBO_TERMINAR_YO', 'grounding': 0.85, 'tipo': 'verbo_fin'},
    'terminas':       {'id': 'VERBO_TERMINAR_TU', 'grounding': 0.85, 'tipo': 'verbo_fin'},
    'termina':        {'id': 'VERBO_TERMINAR_EL', 'grounding': 0.80, 'tipo': 'verbo_fin'},
    'terminar':       {'id': 'VERBO_TERMINAR',    'grounding': 0.85, 'tipo': 'verbo_fin'},
    'terminando':     {'id': 'GERUNDIO_TERMINAR', 'grounding': 0.85, 'tipo': 'gerundio'},
    'terminado':      {'id': 'PART_TERMINAR',     'grounding': 0.80, 'tipo': 'participio'},
    'terminé':        {'id': 'VERBO_TERMINAR_PAS','grounding': 0.80, 'tipo': 'verbo_fin'},
    'terminaste':     {'id': 'VERBO_TERMINAR_PAS2','grounding': 0.80, 'tipo': 'verbo_fin'},

    # ── PASAR / PASAR TIEMPO ─────────────────────────────
    'pasa':           {'id': 'VERBO_PASAR_EL',    'grounding': 0.85, 'tipo': 'verbo_evento'},
    'pasas':          {'id': 'VERBO_PASAR_TU',    'grounding': 0.85, 'tipo': 'verbo_evento'},
    'paso':           {'id': 'VERBO_PASAR_YO',    'grounding': 0.80, 'tipo': 'verbo_evento'},
    'pasar':          {'id': 'VERBO_PASAR',       'grounding': 0.85, 'tipo': 'verbo_evento'},
    'pasando':        {'id': 'GERUNDIO_PASAR',    'grounding': 0.85, 'tipo': 'gerundio'},
    'pasado':         {'id': 'PART_PASAR',        'grounding': 0.80, 'tipo': 'participio'},
    'pasó':           {'id': 'VERBO_PASAR_PAS3',  'grounding': 0.85, 'tipo': 'verbo_evento'},
    'pasé':           {'id': 'VERBO_PASAR_PAS1',  'grounding': 0.80, 'tipo': 'verbo_evento'},
    'pasaste':        {'id': 'VERBO_PASAR_PAS2',  'grounding': 0.80, 'tipo': 'verbo_evento'},

    # ── EXPRESIONES TEMPORALES Y DE PROCESO ──────────────
    'todavía':        {'id': 'TIEMPO_TODAVIA',    'grounding': 0.85, 'tipo': 'tiempo_continuo'},
    'todavia':        {'id': 'TIEMPO_TODAVIA',    'grounding': 0.85, 'tipo': 'tiempo_continuo'},
    'aún':            {'id': 'TIEMPO_TODAVIA',    'grounding': 0.85, 'tipo': 'tiempo_continuo'},
    'aun':            {'id': 'TIEMPO_TODAVIA',    'grounding': 0.80, 'tipo': 'tiempo_continuo'},
    'ya':             {'id': 'TIEMPO_YA',         'grounding': 0.85, 'tipo': 'tiempo_completado'},
    'ahora':          {'id': 'TIEMPO_AHORA',      'grounding': 0.90, 'tipo': 'tiempo_presente'},
    'ahorita':        {'id': 'TIEMPO_AHORA',      'grounding': 0.85, 'tipo': 'tiempo_presente'},
    'ahora mismo':    {'id': 'TIEMPO_AHORA',      'grounding': 0.90, 'tipo': 'tiempo_presente'},
    'hoy':            {'id': 'TIEMPO_HOY',        'grounding': 0.90, 'tipo': 'tiempo_presente'},
    'mañana':         {'id': 'TIEMPO_MANANA',     'grounding': 0.90, 'tipo': 'tiempo_futuro'},
    'manana':         {'id': 'TIEMPO_MANANA',     'grounding': 0.85, 'tipo': 'tiempo_futuro'},
    'ayer':           {'id': 'TIEMPO_AYER',       'grounding': 0.90, 'tipo': 'tiempo_pasado'},
    'antes':          {'id': 'TIEMPO_ANTES',      'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'después':        {'id': 'TIEMPO_DESPUES',    'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'despues':        {'id': 'TIEMPO_DESPUES',    'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'luego':          {'id': 'TIEMPO_DESPUES',    'grounding': 0.85, 'tipo': 'tiempo_relativo'},
    'pronto':         {'id': 'TIEMPO_PRONTO',     'grounding': 0.85, 'tipo': 'tiempo_futuro'},
    'tarde':          {'id': 'TIEMPO_TARDE',      'grounding': 0.80, 'tipo': 'tiempo_relativo'},
    'temprano':       {'id': 'TIEMPO_TEMPRANO',   'grounding': 0.80, 'tipo': 'tiempo_relativo'},
    'siempre':        {'id': 'TIEMPO_SIEMPRE',    'grounding': 0.90, 'tipo': 'tiempo_permanente'},
    'nunca':          {'id': 'TIEMPO_NUNCA',      'grounding': 0.90, 'tipo': 'tiempo_ausente'},
    'a veces':        {'id': 'TIEMPO_A_VECES',    'grounding': 0.85, 'tipo': 'tiempo_frecuencia'},
    'aveces':         {'id': 'TIEMPO_A_VECES',    'grounding': 0.85, 'tipo': 'tiempo_frecuencia'},
    'casi siempre':   {'id': 'TIEMPO_CASI_SIEM',  'grounding': 0.85, 'tipo': 'tiempo_frecuencia'},
    'casi nunca':     {'id': 'TIEMPO_CASI_NUN',   'grounding': 0.85, 'tipo': 'tiempo_frecuencia'},
    'de vez en cuando':{'id': 'TIEMPO_A_VECES',   'grounding': 0.85, 'tipo': 'tiempo_frecuencia'},
    'en este momento': {'id': 'TIEMPO_AHORA',     'grounding': 0.90, 'tipo': 'tiempo_presente'},
    'en este momento':{'id': 'TIEMPO_AHORA',      'grounding': 0.90, 'tipo': 'tiempo_presente'},
    'por ahora':      {'id': 'TIEMPO_POR_AHORA',  'grounding': 0.85, 'tipo': 'tiempo_provisional'},
    'por el momento': {'id': 'TIEMPO_POR_AHORA',  'grounding': 0.85, 'tipo': 'tiempo_provisional'},
    'hace rato':      {'id': 'TIEMPO_HACE_RATO',  'grounding': 0.85, 'tipo': 'tiempo_pasado'},
    'hace tiempo':    {'id': 'TIEMPO_HACE_TIEMPO','grounding': 0.85, 'tipo': 'tiempo_pasado'},
    'hace mucho':     {'id': 'TIEMPO_HACE_MUCHO', 'grounding': 0.85, 'tipo': 'tiempo_pasado'},

    # ── VERBOS DE ESTADO MENTAL / EXISTENCIA ─────────────
    'existo':         {'id': 'VERBO_EXISTIR_YO',  'grounding': 0.90, 'tipo': 'verbo_existencia'},
    'existes':        {'id': 'VERBO_EXISTIR_TU',  'grounding': 0.90, 'tipo': 'verbo_existencia'},
    'existe':         {'id': 'VERBO_EXISTIR_EL',  'grounding': 0.85, 'tipo': 'verbo_existencia'},
    'existir':        {'id': 'VERBO_EXISTIR',     'grounding': 0.85, 'tipo': 'verbo_existencia'},
    'existiendo':     {'id': 'GERUNDIO_EXISTIR',  'grounding': 0.80, 'tipo': 'gerundio'},
    'vivo':           {'id': 'VERBO_VIVIR_YO',    'grounding': 0.85, 'tipo': 'verbo_existencia'},
    'vives':          {'id': 'VERBO_VIVIR_TU',    'grounding': 0.85, 'tipo': 'verbo_existencia'},
    'vivir':          {'id': 'VERBO_VIVIR',       'grounding': 0.85, 'tipo': 'verbo_existencia'},
    'viviendo':       {'id': 'GERUNDIO_VIVIR',    'grounding': 0.80, 'tipo': 'gerundio'},
    'recuerdo':       {'id': 'VERBO_RECORDAR_YO', 'grounding': 0.85, 'tipo': 'verbo_memoria'},
    'recuerdas':      {'id': 'VERBO_RECORDAR_TU', 'grounding': 0.85, 'tipo': 'verbo_memoria'},
    'recuerda':       {'id': 'VERBO_RECORDAR_EL', 'grounding': 0.80, 'tipo': 'verbo_memoria'},
    'recordar':       {'id': 'VERBO_RECORDAR',    'grounding': 0.85, 'tipo': 'verbo_memoria'},
    'recordando':     {'id': 'GERUNDIO_RECORDAR', 'grounding': 0.80, 'tipo': 'gerundio'},
    'recordado':      {'id': 'PART_RECORDAR',     'grounding': 0.75, 'tipo': 'participio'},
    'olvidé':         {'id': 'VERBO_OLVIDAR_PAS', 'grounding': 0.80, 'tipo': 'verbo_memoria'},
    'olvidaste':      {'id': 'VERBO_OLVIDAR_PAS2','grounding': 0.80, 'tipo': 'verbo_memoria'},
    'olvido':         {'id': 'VERBO_OLVIDAR_YO',  'grounding': 0.80, 'tipo': 'verbo_memoria'},
    'olvidando':      {'id': 'GERUNDIO_OLVIDAR',  'grounding': 0.80, 'tipo': 'gerundio'},
    'sigo':           {'id': 'VERBO_SEGUIR_YO',   'grounding': 0.85, 'tipo': 'verbo_continuacion'},
    'sigues':         {'id': 'VERBO_SEGUIR_TU',   'grounding': 0.85, 'tipo': 'verbo_continuacion'},
    'sigue':          {'id': 'VERBO_SEGUIR_EL',   'grounding': 0.85, 'tipo': 'verbo_continuacion'},
    'seguir':         {'id': 'VERBO_SEGUIR',      'grounding': 0.85, 'tipo': 'verbo_continuacion'},
    'siguiendo':      {'id': 'GERUNDIO_SEGUIR',   'grounding': 0.85, 'tipo': 'gerundio'},

    # ── VERBOS DE PRESENTACIÓN SEBASTIAN ─────────────────
    'presento':       {'id': 'VERBO_PRESENTAR_YO','grounding': 0.85, 'tipo': 'verbo_identidad'},
    'presento me':    {'id': 'PRESENTACION_NOMBRE','grounding': 0.90, 'tipo': 'presentacion'},
    'llamo':          {'id': 'PRESENTACION_NOMBRE','grounding': 0.90, 'tipo': 'presentacion'},
    'nombre es':      {'id': 'PRESENTACION_NOMBRE','grounding': 0.90, 'tipo': 'presentacion'},

    # ── VERBOS COMPUESTOS FRECUENTES ─────────────────────
    'estoy haciendo':  {'id': 'EXPR_PRESENTE_CONTINUO', 'grounding': 0.90, 'tipo': 'accion_presente'},
    'estoy pensando':  {'id': 'EXPR_PENSANDO_AHORA',    'grounding': 0.90, 'tipo': 'accion_presente'},
    'estoy aprendiendo':{'id': 'EXPR_APRENDIENDO',       'grounding': 0.90, 'tipo': 'accion_presente'},
    'estoy trabajando':{'id': 'EXPR_TRABAJANDO_AHORA',  'grounding': 0.90, 'tipo': 'accion_presente'},
    'estoy bien':      {'id': 'EMOCION_BIEN',            'grounding': 0.90, 'tipo': 'emocion_positiva'},
    'estoy mal':       {'id': 'EMOCION_MAL',             'grounding': 0.90, 'tipo': 'emocion_negativa'},
    'estoy cansado':   {'id': 'EMOCION_CANSADO',         'grounding': 0.95, 'tipo': 'emocion_negativa'},
    'estoy cansada':   {'id': 'EMOCION_CANSADO',         'grounding': 0.95, 'tipo': 'emocion_negativa'},
    'estoy triste':    {'id': 'EMOCION_TRISTE',          'grounding': 0.95, 'tipo': 'emocion_negativa'},
    'estoy frustrado': {'id': 'EMOCION_FRUSTRADO',       'grounding': 0.95, 'tipo': 'emocion_negativa'},
    'estoy feliz':     {'id': 'EMOCION_FELIZ',           'grounding': 0.95, 'tipo': 'emocion_positiva'},
    'estoy perdido':   {'id': 'EMOCION_CONFUNDIDO',      'grounding': 0.90, 'tipo': 'emocion_negativa'},
    'no entiendo nada':{'id': 'EXPR_CONFUSION_TOTAL',    'grounding': 0.95, 'tipo': 'confusion'},
    'no sé qué hacer': {'id': 'EXPR_NO_SABE_QUE_HACER', 'grounding': 0.95, 'tipo': 'confusion'},
    'no sé por dónde': {'id': 'EXPR_SIN_ORIENTACION',   'grounding': 0.90, 'tipo': 'confusion'},
    'no sé por donde': {'id': 'EXPR_SIN_ORIENTACION',   'grounding': 0.90, 'tipo': 'confusion'},
    'tengo que':       {'id': 'EXPR_OBLIGACION',         'grounding': 0.90, 'tipo': 'necesidad'},
    'hay que':         {'id': 'EXPR_OBLIGACION',         'grounding': 0.90, 'tipo': 'necesidad'},
    'voy a':           {'id': 'EXPR_INTENCION_FUT',      'grounding': 0.90, 'tipo': 'intencion_futura'},
    'vamos a':         {'id': 'EXPR_INTENCION_FUT',      'grounding': 0.90, 'tipo': 'intencion_futura'},
    'acabo de':        {'id': 'EXPR_RECIEN_HECHO',       'grounding': 0.90, 'tipo': 'tiempo_reciente'},
    'acabas de':       {'id': 'EXPR_RECIEN_HECHO',       'grounding': 0.90, 'tipo': 'tiempo_reciente'},
    'dejé de':         {'id': 'EXPR_DETUVO',             'grounding': 0.85, 'tipo': 'fin_accion'},
    'dejaste de':      {'id': 'EXPR_DETUVO',             'grounding': 0.85, 'tipo': 'fin_accion'},
    'siguió':          {'id': 'EXPR_CONTINUO',           'grounding': 0.80, 'tipo': 'continuacion'},
}